/* tslint:disable */
/* eslint-disable */
/**
 * EasyLog API Programmatic access to EasyLog REST endpoints
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
import type { Announcement } from './Announcement';
import {
  AnnouncementFromJSON,
  AnnouncementFromJSONTyped,
  AnnouncementToJSON,
  AnnouncementToJSONTyped
} from './Announcement';

/**
 * @export
 * @interface AnnouncementCollection
 */
export interface AnnouncementCollection {
  /**
   * @memberof AnnouncementCollection
   * @type {Announcement[]}
   */
  data?: Array<Announcement>;
}

/** Check if a given object implements the AnnouncementCollection interface. */
export function instanceOfAnnouncementCollection(
  value: object
): value is AnnouncementCollection {
  return true;
}

export function AnnouncementCollectionFromJSON(
  json: any
): AnnouncementCollection {
  return AnnouncementCollectionFromJSONTyped(json, false);
}

export function AnnouncementCollectionFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): AnnouncementCollection {
  if (json == null) {
    return json;
  }
  return {
    data:
      json['data'] == null
        ? undefined
        : (json['data'] as Array<any>).map(AnnouncementFromJSON)
  };
}

export function AnnouncementCollectionToJSON(
  json: any
): AnnouncementCollection {
  return AnnouncementCollectionToJSONTyped(json, false);
}

export function AnnouncementCollectionToJSONTyped(
  value?: AnnouncementCollection | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    data:
      value['data'] == null
        ? undefined
        : (value['data'] as Array<any>).map(AnnouncementToJSON)
  };
}
