/* tslint:disable */
/* eslint-disable */
/**
 * EasyLog API Programmatic access to EasyLog REST endpoints
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
/**
 * @export
 * @interface AnnouncementStatusInput
 */
export interface AnnouncementStatusInput {
  /**
   * @memberof AnnouncementStatusInput
   * @type {string}
   */
  status: AnnouncementStatusInputStatusEnum;
  /**
   * Required when status is 'opened_attachment'
   *
   * @memberof AnnouncementStatusInput
   * @type {number}
   */
  mediaId?: number | null;
}

/** @export */
export const AnnouncementStatusInputStatusEnum = {
  Retrieved: 'retrieved',
  Opened: 'opened',
  ScrolledDown: 'scrolled_down',
  OpenedAttachment: 'opened_attachment',
  ConfirmedMessagesRead: 'confirmed_messages_read'
} as const;
export type AnnouncementStatusInputStatusEnum =
  (typeof AnnouncementStatusInputStatusEnum)[keyof typeof AnnouncementStatusInputStatusEnum];

/** Check if a given object implements the AnnouncementStatusInput interface. */
export function instanceOfAnnouncementStatusInput(
  value: object
): value is AnnouncementStatusInput {
  if (!('status' in value) || value['status'] === undefined) return false;
  return true;
}

export function AnnouncementStatusInputFromJSON(
  json: any
): AnnouncementStatusInput {
  return AnnouncementStatusInputFromJSONTyped(json, false);
}

export function AnnouncementStatusInputFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): AnnouncementStatusInput {
  if (json == null) {
    return json;
  }
  return {
    status: json['status'],
    mediaId: json['media_id'] == null ? undefined : json['media_id']
  };
}

export function AnnouncementStatusInputToJSON(
  json: any
): AnnouncementStatusInput {
  return AnnouncementStatusInputToJSONTyped(json, false);
}

export function AnnouncementStatusInputToJSONTyped(
  value?: AnnouncementStatusInput | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    status: value['status'],
    media_id: value['mediaId']
  };
}
