/* tslint:disable */
/* eslint-disable */
/**
 * EasyLog API
 * Programmatic access to EasyLog REST endpoints
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AnnouncementCategory
 */
export interface AnnouncementCategory {
    /**
     * 
     * @type {number}
     * @memberof AnnouncementCategory
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof AnnouncementCategory
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof AnnouncementCategory
     */
    icon?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AnnouncementCategory
     */
    color?: string | null;
}

/**
 * Check if a given object implements the AnnouncementCategory interface.
 */
export function instanceOfAnnouncementCategory(value: object): value is AnnouncementCategory {
    return true;
}

export function AnnouncementCategoryFromJSON(json: any): AnnouncementCategory {
    return AnnouncementCategoryFromJSONTyped(json, false);
}

export function AnnouncementCategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnnouncementCategory {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'icon': json['icon'] == null ? undefined : json['icon'],
        'color': json['color'] == null ? undefined : json['color'],
    };
}

export function AnnouncementCategoryToJSON(json: any): AnnouncementCategory {
    return AnnouncementCategoryToJSONTyped(json, false);
}

export function AnnouncementCategoryToJSONTyped(value?: AnnouncementCategory | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'icon': value['icon'],
        'color': value['color'],
    };
}

