/* tslint:disable */
/* eslint-disable */
/**
 * EasyLog API Programmatic access to EasyLog REST endpoints
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
import type { Announcement } from './Announcement';
import {
  AnnouncementFromJSON,
  AnnouncementFromJSONTyped,
  AnnouncementToJSON,
  AnnouncementToJSONTyped
} from './Announcement';

/**
 * @export
 * @interface AnnouncementResource
 */
export interface AnnouncementResource {
  /**
   * @memberof AnnouncementResource
   * @type {Announcement}
   */
  data?: Announcement;
}

/** Check if a given object implements the AnnouncementResource interface. */
export function instanceOfAnnouncementResource(
  value: object
): value is AnnouncementResource {
  return true;
}

export function AnnouncementResourceFromJSON(json: any): AnnouncementResource {
  return AnnouncementResourceFromJSONTyped(json, false);
}

export function AnnouncementResourceFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): AnnouncementResource {
  if (json == null) {
    return json;
  }
  return {
    data: json['data'] == null ? undefined : AnnouncementFromJSON(json['data'])
  };
}

export function AnnouncementResourceToJSON(json: any): AnnouncementResource {
  return AnnouncementResourceToJSONTyped(json, false);
}

export function AnnouncementResourceToJSONTyped(
  value?: AnnouncementResource | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    data: AnnouncementToJSON(value['data'])
  };
}
