/* tslint:disable */
/* eslint-disable */
/**
 * EasyLog API
 * Programmatic access to EasyLog REST endpoints
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AnnouncementSender
 */
export interface AnnouncementSender {
    /**
     * 
     * @type {string}
     * @memberof AnnouncementSender
     */
    fullname?: string;
}

/**
 * Check if a given object implements the AnnouncementSender interface.
 */
export function instanceOfAnnouncementSender(value: object): value is AnnouncementSender {
    return true;
}

export function AnnouncementSenderFromJSON(json: any): AnnouncementSender {
    return AnnouncementSenderFromJSONTyped(json, false);
}

export function AnnouncementSenderFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnnouncementSender {
    if (json == null) {
        return json;
    }
    return {
        
        'fullname': json['fullname'] == null ? undefined : json['fullname'],
    };
}

export function AnnouncementSenderToJSON(json: any): AnnouncementSender {
    return AnnouncementSenderToJSONTyped(json, false);
}

export function AnnouncementSenderToJSONTyped(value?: AnnouncementSender | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fullname': value['fullname'],
    };
}

