/* tslint:disable */
/* eslint-disable */
/**
 * EasyLog API
 * Programmatic access to EasyLog REST endpoints
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BulletinItem
 */
export interface BulletinItem {
    /**
     * 
     * @type {number}
     * @memberof BulletinItem
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof BulletinItem
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof BulletinItem
     */
    content?: string;
    /**
     * Bulletin item type (e.g., pdf, annotated_pdf)
     * @type {string}
     * @memberof BulletinItem
     */
    type?: string | null;
    /**
     * 
     * @type {number}
     * @memberof BulletinItem
     */
    bulletinChapterId?: number | null;
}

/**
 * Check if a given object implements the BulletinItem interface.
 */
export function instanceOfBulletinItem(value: object): value is BulletinItem {
    return true;
}

export function BulletinItemFromJSON(json: any): BulletinItem {
    return BulletinItemFromJSONTyped(json, false);
}

export function BulletinItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): BulletinItem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'content': json['content'] == null ? undefined : json['content'],
        'type': json['type'] == null ? undefined : json['type'],
        'bulletinChapterId': json['bulletin_chapter_id'] == null ? undefined : json['bulletin_chapter_id'],
    };
}

export function BulletinItemToJSON(json: any): BulletinItem {
    return BulletinItemToJSONTyped(json, false);
}

export function BulletinItemToJSONTyped(value?: BulletinItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'content': value['content'],
        'type': value['type'],
        'bulletin_chapter_id': value['bulletinChapterId'],
    };
}

