/* tslint:disable */
/* eslint-disable */
/**
 * EasyLog API
 * Programmatic access to EasyLog REST endpoints
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BulletinChapter } from './BulletinChapter';
import {
    BulletinChapterFromJSON,
    BulletinChapterFromJSONTyped,
    BulletinChapterToJSON,
    BulletinChapterToJSONTyped,
} from './BulletinChapter';

/**
 * 
 * @export
 * @interface BulletinChapterCollection
 */
export interface BulletinChapterCollection {
    /**
     * 
     * @type {Array<BulletinChapter>}
     * @memberof BulletinChapterCollection
     */
    data?: Array<BulletinChapter>;
}

/**
 * Check if a given object implements the BulletinChapterCollection interface.
 */
export function instanceOfBulletinChapterCollection(value: object): value is BulletinChapterCollection {
    return true;
}

export function BulletinChapterCollectionFromJSON(json: any): BulletinChapterCollection {
    return BulletinChapterCollectionFromJSONTyped(json, false);
}

export function BulletinChapterCollectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): BulletinChapterCollection {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(BulletinChapterFromJSON)),
    };
}

export function BulletinChapterCollectionToJSON(json: any): BulletinChapterCollection {
    return BulletinChapterCollectionToJSONTyped(json, false);
}

export function BulletinChapterCollectionToJSONTyped(value?: BulletinChapterCollection | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(BulletinChapterToJSON)),
    };
}

