/* tslint:disable */
/* eslint-disable */
/**
 * EasyLog API
 * Programmatic access to EasyLog REST endpoints
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BulletinItem } from './BulletinItem';
import {
    BulletinItemFromJSON,
    BulletinItemFromJSONTyped,
    BulletinItemToJSON,
    BulletinItemToJSONTyped,
} from './BulletinItem';

/**
 * 
 * @export
 * @interface BulletinChapter
 */
export interface BulletinChapter {
    /**
     * 0 for unchaptered items
     * @type {number}
     * @memberof BulletinChapter
     */
    id?: number;
    /**
     * Chapter title, empty for unchaptered items
     * @type {string}
     * @memberof BulletinChapter
     */
    title?: string;
    /**
     * Bulletin items in this chapter
     * @type {Array<BulletinItem>}
     * @memberof BulletinChapter
     */
    items?: Array<BulletinItem>;
    /**
     * Nested sub-chapters
     * @type {Array<BulletinChapter>}
     * @memberof BulletinChapter
     */
    chapters?: Array<BulletinChapter>;
}

/**
 * Check if a given object implements the BulletinChapter interface.
 */
export function instanceOfBulletinChapter(value: object): value is BulletinChapter {
    return true;
}

export function BulletinChapterFromJSON(json: any): BulletinChapter {
    return BulletinChapterFromJSONTyped(json, false);
}

export function BulletinChapterFromJSONTyped(json: any, ignoreDiscriminator: boolean): BulletinChapter {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(BulletinItemFromJSON)),
        'chapters': json['chapters'] == null ? undefined : ((json['chapters'] as Array<any>).map(BulletinChapterFromJSON)),
    };
}

export function BulletinChapterToJSON(json: any): BulletinChapter {
    return BulletinChapterToJSONTyped(json, false);
}

export function BulletinChapterToJSONTyped(value?: BulletinChapter | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(BulletinItemToJSON)),
        'chapters': value['chapters'] == null ? undefined : ((value['chapters'] as Array<any>).map(BulletinChapterToJSON)),
    };
}

