/* tslint:disable */
/* eslint-disable */
/**
 * EasyLog API Programmatic access to EasyLog REST endpoints
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
import type { Category } from './Category';
import {
  CategoryFromJSON,
  CategoryFromJSONTyped,
  CategoryToJSON,
  CategoryToJSONTyped
} from './Category';

/**
 * @export
 * @interface CategoryResource
 */
export interface CategoryResource {
  /**
   * @memberof CategoryResource
   * @type {Category}
   */
  data?: Category;
}

/** Check if a given object implements the CategoryResource interface. */
export function instanceOfCategoryResource(
  value: object
): value is CategoryResource {
  return true;
}

export function CategoryResourceFromJSON(json: any): CategoryResource {
  return CategoryResourceFromJSONTyped(json, false);
}

export function CategoryResourceFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): CategoryResource {
  if (json == null) {
    return json;
  }
  return {
    data: json['data'] == null ? undefined : CategoryFromJSON(json['data'])
  };
}

export function CategoryResourceToJSON(json: any): CategoryResource {
  return CategoryResourceToJSONTyped(json, false);
}

export function CategoryResourceToJSONTyped(
  value?: CategoryResource | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    data: CategoryToJSON(value['data'])
  };
}
