/* tslint:disable */
/* eslint-disable */
/**
 * EasyLog API Programmatic access to EasyLog REST endpoints
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
/**
 * @export
 * @interface CategoryCollectionLinks
 */
export interface CategoryCollectionLinks {
  /**
   * @memberof CategoryCollectionLinks
   * @type {string}
   */
  first?: string | null;
  /**
   * @memberof CategoryCollectionLinks
   * @type {string}
   */
  last?: string | null;
  /**
   * @memberof CategoryCollectionLinks
   * @type {string}
   */
  prev?: string | null;
  /**
   * @memberof CategoryCollectionLinks
   * @type {string}
   */
  next?: string | null;
}

/** Check if a given object implements the CategoryCollectionLinks interface. */
export function instanceOfCategoryCollectionLinks(
  value: object
): value is CategoryCollectionLinks {
  return true;
}

export function CategoryCollectionLinksFromJSON(
  json: any
): CategoryCollectionLinks {
  return CategoryCollectionLinksFromJSONTyped(json, false);
}

export function CategoryCollectionLinksFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): CategoryCollectionLinks {
  if (json == null) {
    return json;
  }
  return {
    first: json['first'] == null ? undefined : json['first'],
    last: json['last'] == null ? undefined : json['last'],
    prev: json['prev'] == null ? undefined : json['prev'],
    next: json['next'] == null ? undefined : json['next']
  };
}

export function CategoryCollectionLinksToJSON(
  json: any
): CategoryCollectionLinks {
  return CategoryCollectionLinksToJSONTyped(json, false);
}

export function CategoryCollectionLinksToJSONTyped(
  value?: CategoryCollectionLinks | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    first: value['first'],
    last: value['last'],
    prev: value['prev'],
    next: value['next']
  };
}
