/* tslint:disable */
/* eslint-disable */
/**
 * EasyLog API Programmatic access to EasyLog REST endpoints
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
import type { Category } from './Category';
import {
  CategoryFromJSON,
  CategoryFromJSONTyped,
  CategoryToJSON,
  CategoryToJSONTyped
} from './Category';

/**
 * @export
 * @interface CategoryCollection
 */
export interface CategoryCollection {
  /**
   * @memberof CategoryCollection
   * @type {Category[]}
   */
  data?: Array<Category>;
}

/** Check if a given object implements the CategoryCollection interface. */
export function instanceOfCategoryCollection(
  value: object
): value is CategoryCollection {
  return true;
}

export function CategoryCollectionFromJSON(json: any): CategoryCollection {
  return CategoryCollectionFromJSONTyped(json, false);
}

export function CategoryCollectionFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): CategoryCollection {
  if (json == null) {
    return json;
  }
  return {
    data:
      json['data'] == null
        ? undefined
        : (json['data'] as Array<any>).map(CategoryFromJSON)
  };
}

export function CategoryCollectionToJSON(json: any): CategoryCollection {
  return CategoryCollectionToJSONTyped(json, false);
}

export function CategoryCollectionToJSONTyped(
  value?: CategoryCollection | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    data:
      value['data'] == null
        ? undefined
        : (value['data'] as Array<any>).map(CategoryToJSON)
  };
}
