/* tslint:disable */
/* eslint-disable */
/**
 * EasyLog API
 * Programmatic access to EasyLog REST endpoints
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CategoryCollectionMeta
 */
export interface CategoryCollectionMeta {
    /**
     * 
     * @type {number}
     * @memberof CategoryCollectionMeta
     */
    currentPage?: number;
    /**
     * 
     * @type {number}
     * @memberof CategoryCollectionMeta
     */
    from?: number | null;
    /**
     * 
     * @type {number}
     * @memberof CategoryCollectionMeta
     */
    lastPage?: number;
    /**
     * 
     * @type {number}
     * @memberof CategoryCollectionMeta
     */
    perPage?: number;
    /**
     * 
     * @type {number}
     * @memberof CategoryCollectionMeta
     */
    to?: number | null;
    /**
     * 
     * @type {number}
     * @memberof CategoryCollectionMeta
     */
    total?: number;
}

/**
 * Check if a given object implements the CategoryCollectionMeta interface.
 */
export function instanceOfCategoryCollectionMeta(value: object): value is CategoryCollectionMeta {
    return true;
}

export function CategoryCollectionMetaFromJSON(json: any): CategoryCollectionMeta {
    return CategoryCollectionMetaFromJSONTyped(json, false);
}

export function CategoryCollectionMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategoryCollectionMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'currentPage': json['current_page'] == null ? undefined : json['current_page'],
        'from': json['from'] == null ? undefined : json['from'],
        'lastPage': json['last_page'] == null ? undefined : json['last_page'],
        'perPage': json['per_page'] == null ? undefined : json['per_page'],
        'to': json['to'] == null ? undefined : json['to'],
        'total': json['total'] == null ? undefined : json['total'],
    };
}

export function CategoryCollectionMetaToJSON(json: any): CategoryCollectionMeta {
    return CategoryCollectionMetaToJSONTyped(json, false);
}

export function CategoryCollectionMetaToJSONTyped(value?: CategoryCollectionMeta | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'current_page': value['currentPage'],
        'from': value['from'],
        'last_page': value['lastPage'],
        'per_page': value['perPage'],
        'to': value['to'],
        'total': value['total'],
    };
}

