/* tslint:disable */
/* eslint-disable */
/**
 * EasyLog API
 * Programmatic access to EasyLog REST endpoints
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * User permissions
 * @export
 * @interface ClientConfigurationCan
 */
export interface ClientConfigurationCan {
    /**
     * 
     * @type {boolean}
     * @memberof ClientConfigurationCan
     */
    editPlanning?: boolean;
}

/**
 * Check if a given object implements the ClientConfigurationCan interface.
 */
export function instanceOfClientConfigurationCan(value: object): value is ClientConfigurationCan {
    return true;
}

export function ClientConfigurationCanFromJSON(json: any): ClientConfigurationCan {
    return ClientConfigurationCanFromJSONTyped(json, false);
}

export function ClientConfigurationCanFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClientConfigurationCan {
    if (json == null) {
        return json;
    }
    return {
        
        'editPlanning': json['edit-planning'] == null ? undefined : json['edit-planning'],
    };
}

export function ClientConfigurationCanToJSON(json: any): ClientConfigurationCan {
    return ClientConfigurationCanToJSONTyped(json, false);
}

export function ClientConfigurationCanToJSONTyped(value?: ClientConfigurationCan | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'edit-planning': value['editPlanning'],
    };
}

