/* tslint:disable */
/* eslint-disable */
/**
 * EasyLog API
 * Programmatic access to EasyLog REST endpoints
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ClientConfigurationFiltersInner
 */
export interface ClientConfigurationFiltersInner {
    /**
     * 
     * @type {string}
     * @memberof ClientConfigurationFiltersInner
     */
    field?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientConfigurationFiltersInner
     */
    label?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ClientConfigurationFiltersInner
     */
    enabled?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof ClientConfigurationFiltersInner
     */
    slugs?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ClientConfigurationFiltersInner
     */
    options?: Array<string>;
}

/**
 * Check if a given object implements the ClientConfigurationFiltersInner interface.
 */
export function instanceOfClientConfigurationFiltersInner(value: object): value is ClientConfigurationFiltersInner {
    return true;
}

export function ClientConfigurationFiltersInnerFromJSON(json: any): ClientConfigurationFiltersInner {
    return ClientConfigurationFiltersInnerFromJSONTyped(json, false);
}

export function ClientConfigurationFiltersInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClientConfigurationFiltersInner {
    if (json == null) {
        return json;
    }
    return {
        
        'field': json['field'] == null ? undefined : json['field'],
        'label': json['label'] == null ? undefined : json['label'],
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'slugs': json['slugs'] == null ? undefined : json['slugs'],
        'options': json['options'] == null ? undefined : json['options'],
    };
}

export function ClientConfigurationFiltersInnerToJSON(json: any): ClientConfigurationFiltersInner {
    return ClientConfigurationFiltersInnerToJSONTyped(json, false);
}

export function ClientConfigurationFiltersInnerToJSONTyped(value?: ClientConfigurationFiltersInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'field': value['field'],
        'label': value['label'],
        'enabled': value['enabled'],
        'slugs': value['slugs'],
        'options': value['options'],
    };
}

