/* tslint:disable */
/* eslint-disable */
/**
 * EasyLog API Programmatic access to EasyLog REST endpoints
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
import type { ClientConfiguration } from './ClientConfiguration';
import {
  ClientConfigurationFromJSON,
  ClientConfigurationFromJSONTyped,
  ClientConfigurationToJSON,
  ClientConfigurationToJSONTyped
} from './ClientConfiguration';

/**
 * @export
 * @interface ClientConfigurationResource
 */
export interface ClientConfigurationResource {
  /**
   * @memberof ClientConfigurationResource
   * @type {ClientConfiguration}
   */
  data?: ClientConfiguration;
}

/** Check if a given object implements the ClientConfigurationResource interface. */
export function instanceOfClientConfigurationResource(
  value: object
): value is ClientConfigurationResource {
  return true;
}

export function ClientConfigurationResourceFromJSON(
  json: any
): ClientConfigurationResource {
  return ClientConfigurationResourceFromJSONTyped(json, false);
}

export function ClientConfigurationResourceFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ClientConfigurationResource {
  if (json == null) {
    return json;
  }
  return {
    data:
      json['data'] == null
        ? undefined
        : ClientConfigurationFromJSON(json['data'])
  };
}

export function ClientConfigurationResourceToJSON(
  json: any
): ClientConfigurationResource {
  return ClientConfigurationResourceToJSONTyped(json, false);
}

export function ClientConfigurationResourceToJSONTyped(
  value?: ClientConfigurationResource | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    data: ClientConfigurationToJSON(value['data'])
  };
}
