/* tslint:disable */
/* eslint-disable */
/**
 * EasyLog API
 * Programmatic access to EasyLog REST endpoints
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EntityAllocationUpdateBulkPayloadAllocationsInner } from './EntityAllocationUpdateBulkPayloadAllocationsInner';
import {
    EntityAllocationUpdateBulkPayloadAllocationsInnerFromJSON,
    EntityAllocationUpdateBulkPayloadAllocationsInnerFromJSONTyped,
    EntityAllocationUpdateBulkPayloadAllocationsInnerToJSON,
    EntityAllocationUpdateBulkPayloadAllocationsInnerToJSONTyped,
} from './EntityAllocationUpdateBulkPayloadAllocationsInner';

/**
 * 
 * @export
 * @interface EntityAllocationUpdateBulkPayload
 */
export interface EntityAllocationUpdateBulkPayload {
    /**
     * 
     * @type {Array<EntityAllocationUpdateBulkPayloadAllocationsInner>}
     * @memberof EntityAllocationUpdateBulkPayload
     */
    allocations: Array<EntityAllocationUpdateBulkPayloadAllocationsInner>;
}

/**
 * Check if a given object implements the EntityAllocationUpdateBulkPayload interface.
 */
export function instanceOfEntityAllocationUpdateBulkPayload(value: object): value is EntityAllocationUpdateBulkPayload {
    if (!('allocations' in value) || value['allocations'] === undefined) return false;
    return true;
}

export function EntityAllocationUpdateBulkPayloadFromJSON(json: any): EntityAllocationUpdateBulkPayload {
    return EntityAllocationUpdateBulkPayloadFromJSONTyped(json, false);
}

export function EntityAllocationUpdateBulkPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntityAllocationUpdateBulkPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'allocations': ((json['allocations'] as Array<any>).map(EntityAllocationUpdateBulkPayloadAllocationsInnerFromJSON)),
    };
}

export function EntityAllocationUpdateBulkPayloadToJSON(json: any): EntityAllocationUpdateBulkPayload {
    return EntityAllocationUpdateBulkPayloadToJSONTyped(json, false);
}

export function EntityAllocationUpdateBulkPayloadToJSONTyped(value?: EntityAllocationUpdateBulkPayload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'allocations': ((value['allocations'] as Array<any>).map(EntityAllocationUpdateBulkPayloadAllocationsInnerToJSON)),
    };
}

