/* tslint:disable */
/* eslint-disable */
/**
 * EasyLog API Programmatic access to EasyLog REST endpoints
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
/**
 * @export
 * @interface EntityResourceGroupsInner
 */
export interface EntityResourceGroupsInner {
  /**
   * @memberof EntityResourceGroupsInner
   * @type {string}
   */
  name: string;
  /**
   * @memberof EntityResourceGroupsInner
   * @type {string}
   */
  label: string;
  /**
   * @memberof EntityResourceGroupsInner
   * @type {string}
   */
  slug: string;
}

/** Check if a given object implements the EntityResourceGroupsInner interface. */
export function instanceOfEntityResourceGroupsInner(
  value: object
): value is EntityResourceGroupsInner {
  if (!('name' in value) || value['name'] === undefined) return false;
  if (!('label' in value) || value['label'] === undefined) return false;
  if (!('slug' in value) || value['slug'] === undefined) return false;
  return true;
}

export function EntityResourceGroupsInnerFromJSON(
  json: any
): EntityResourceGroupsInner {
  return EntityResourceGroupsInnerFromJSONTyped(json, false);
}

export function EntityResourceGroupsInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): EntityResourceGroupsInner {
  if (json == null) {
    return json;
  }
  return {
    name: json['name'],
    label: json['label'],
    slug: json['slug']
  };
}

export function EntityResourceGroupsInnerToJSON(
  json: any
): EntityResourceGroupsInner {
  return EntityResourceGroupsInnerToJSONTyped(json, false);
}

export function EntityResourceGroupsInnerToJSONTyped(
  value?: EntityResourceGroupsInner | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    name: value['name'],
    label: value['label'],
    slug: value['slug']
  };
}
