/* tslint:disable */
/* eslint-disable */
/**
 * EasyLog API
 * Programmatic access to EasyLog REST endpoints
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EntityAllocationPayload
 */
export interface EntityAllocationPayload {
    /**
     * 
     * @type {number}
     * @memberof EntityAllocationPayload
     */
    projectId: number;
    /**
     * 
     * @type {number}
     * @memberof EntityAllocationPayload
     */
    resourceId: number;
    /**
     * 
     * @type {string}
     * @memberof EntityAllocationPayload
     */
    group?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EntityAllocationPayload
     */
    type?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EntityAllocationPayload
     */
    comment?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof EntityAllocationPayload
     */
    start: Date;
    /**
     * 
     * @type {Date}
     * @memberof EntityAllocationPayload
     */
    end: Date;
    /**
     * Additional allocation fields as key-value pairs. Values can be strings, numbers, booleans, objects, or arrays. Allowed fields depend on the resource configuration.
     * @type {object}
     * @memberof EntityAllocationPayload
     */
    fields?: object | null;
}

/**
 * Check if a given object implements the EntityAllocationPayload interface.
 */
export function instanceOfEntityAllocationPayload(value: object): value is EntityAllocationPayload {
    if (!('projectId' in value) || value['projectId'] === undefined) return false;
    if (!('resourceId' in value) || value['resourceId'] === undefined) return false;
    if (!('start' in value) || value['start'] === undefined) return false;
    if (!('end' in value) || value['end'] === undefined) return false;
    return true;
}

export function EntityAllocationPayloadFromJSON(json: any): EntityAllocationPayload {
    return EntityAllocationPayloadFromJSONTyped(json, false);
}

export function EntityAllocationPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntityAllocationPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'projectId': json['project_id'],
        'resourceId': json['resource_id'],
        'group': json['group'] == null ? undefined : json['group'],
        'type': json['type'] == null ? undefined : json['type'],
        'comment': json['comment'] == null ? undefined : json['comment'],
        'start': (new Date(json['start'])),
        'end': (new Date(json['end'])),
        'fields': json['fields'] == null ? undefined : json['fields'],
    };
}

export function EntityAllocationPayloadToJSON(json: any): EntityAllocationPayload {
    return EntityAllocationPayloadToJSONTyped(json, false);
}

export function EntityAllocationPayloadToJSONTyped(value?: EntityAllocationPayload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'project_id': value['projectId'],
        'resource_id': value['resourceId'],
        'group': value['group'],
        'type': value['type'],
        'comment': value['comment'],
        'start': value['start'].toISOString(),
        'end': value['end'].toISOString(),
        'fields': value['fields'],
    };
}

