/* tslint:disable */
/* eslint-disable */
/**
 * EasyLog API
 * Programmatic access to EasyLog REST endpoints
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FollowUpEntryInput
 */
export interface FollowUpEntryInput {
    /**
     * 
     * @type {object}
     * @memberof FollowUpEntryInput
     */
    data: object;
}

/**
 * Check if a given object implements the FollowUpEntryInput interface.
 */
export function instanceOfFollowUpEntryInput(value: object): value is FollowUpEntryInput {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function FollowUpEntryInputFromJSON(json: any): FollowUpEntryInput {
    return FollowUpEntryInputFromJSONTyped(json, false);
}

export function FollowUpEntryInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): FollowUpEntryInput {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'],
    };
}

export function FollowUpEntryInputToJSON(json: any): FollowUpEntryInput {
    return FollowUpEntryInputToJSONTyped(json, false);
}

export function FollowUpEntryInputToJSONTyped(value?: FollowUpEntryInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'],
    };
}

