/* tslint:disable */
/* eslint-disable */
/**
 * EasyLog API
 * Programmatic access to EasyLog REST endpoints
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FollowUpCategory } from './FollowUpCategory';
import {
    FollowUpCategoryFromJSON,
    FollowUpCategoryFromJSONTyped,
    FollowUpCategoryToJSON,
    FollowUpCategoryToJSONTyped,
} from './FollowUpCategory';

/**
 * 
 * @export
 * @interface FollowUpCategoryResource
 */
export interface FollowUpCategoryResource {
    /**
     * 
     * @type {FollowUpCategory}
     * @memberof FollowUpCategoryResource
     */
    data?: FollowUpCategory;
}

/**
 * Check if a given object implements the FollowUpCategoryResource interface.
 */
export function instanceOfFollowUpCategoryResource(value: object): value is FollowUpCategoryResource {
    return true;
}

export function FollowUpCategoryResourceFromJSON(json: any): FollowUpCategoryResource {
    return FollowUpCategoryResourceFromJSONTyped(json, false);
}

export function FollowUpCategoryResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): FollowUpCategoryResource {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : FollowUpCategoryFromJSON(json['data']),
    };
}

export function FollowUpCategoryResourceToJSON(json: any): FollowUpCategoryResource {
    return FollowUpCategoryResourceToJSONTyped(json, false);
}

export function FollowUpCategoryResourceToJSONTyped(value?: FollowUpCategoryResource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': FollowUpCategoryToJSON(value['data']),
    };
}

