/* tslint:disable */
/* eslint-disable */
/**
 * EasyLog API
 * Programmatic access to EasyLog REST endpoints
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FollowUpEntry } from './FollowUpEntry';
import {
    FollowUpEntryFromJSON,
    FollowUpEntryFromJSONTyped,
    FollowUpEntryToJSON,
    FollowUpEntryToJSONTyped,
} from './FollowUpEntry';

/**
 * 
 * @export
 * @interface FollowUpEntryResource
 */
export interface FollowUpEntryResource {
    /**
     * 
     * @type {FollowUpEntry}
     * @memberof FollowUpEntryResource
     */
    data?: FollowUpEntry;
}

/**
 * Check if a given object implements the FollowUpEntryResource interface.
 */
export function instanceOfFollowUpEntryResource(value: object): value is FollowUpEntryResource {
    return true;
}

export function FollowUpEntryResourceFromJSON(json: any): FollowUpEntryResource {
    return FollowUpEntryResourceFromJSONTyped(json, false);
}

export function FollowUpEntryResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): FollowUpEntryResource {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : FollowUpEntryFromJSON(json['data']),
    };
}

export function FollowUpEntryResourceToJSON(json: any): FollowUpEntryResource {
    return FollowUpEntryResourceToJSONTyped(json, false);
}

export function FollowUpEntryResourceToJSONTyped(value?: FollowUpEntryResource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': FollowUpEntryToJSON(value['data']),
    };
}

