/* tslint:disable */
/* eslint-disable */
/**
 * EasyLog API
 * Programmatic access to EasyLog REST endpoints
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CategoryCollectionLinks } from './CategoryCollectionLinks';
import {
    CategoryCollectionLinksFromJSON,
    CategoryCollectionLinksFromJSONTyped,
    CategoryCollectionLinksToJSON,
    CategoryCollectionLinksToJSONTyped,
} from './CategoryCollectionLinks';
import type { CategoryCollectionMeta } from './CategoryCollectionMeta';
import {
    CategoryCollectionMetaFromJSON,
    CategoryCollectionMetaFromJSONTyped,
    CategoryCollectionMetaToJSON,
    CategoryCollectionMetaToJSONTyped,
} from './CategoryCollectionMeta';
import type { FollowUpCategory } from './FollowUpCategory';
import {
    FollowUpCategoryFromJSON,
    FollowUpCategoryFromJSONTyped,
    FollowUpCategoryToJSON,
    FollowUpCategoryToJSONTyped,
} from './FollowUpCategory';

/**
 * Paginated collection of follow-up categories
 * @export
 * @interface FollowUpCategoryCollection
 */
export interface FollowUpCategoryCollection {
    /**
     * 
     * @type {Array<FollowUpCategory>}
     * @memberof FollowUpCategoryCollection
     */
    data?: Array<FollowUpCategory>;
    /**
     * 
     * @type {CategoryCollectionLinks}
     * @memberof FollowUpCategoryCollection
     */
    links?: CategoryCollectionLinks;
    /**
     * 
     * @type {CategoryCollectionMeta}
     * @memberof FollowUpCategoryCollection
     */
    meta?: CategoryCollectionMeta;
}

/**
 * Check if a given object implements the FollowUpCategoryCollection interface.
 */
export function instanceOfFollowUpCategoryCollection(value: object): value is FollowUpCategoryCollection {
    return true;
}

export function FollowUpCategoryCollectionFromJSON(json: any): FollowUpCategoryCollection {
    return FollowUpCategoryCollectionFromJSONTyped(json, false);
}

export function FollowUpCategoryCollectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): FollowUpCategoryCollection {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(FollowUpCategoryFromJSON)),
        'links': json['links'] == null ? undefined : CategoryCollectionLinksFromJSON(json['links']),
        'meta': json['meta'] == null ? undefined : CategoryCollectionMetaFromJSON(json['meta']),
    };
}

export function FollowUpCategoryCollectionToJSON(json: any): FollowUpCategoryCollection {
    return FollowUpCategoryCollectionToJSONTyped(json, false);
}

export function FollowUpCategoryCollectionToJSONTyped(value?: FollowUpCategoryCollection | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(FollowUpCategoryToJSON)),
        'links': CategoryCollectionLinksToJSON(value['links']),
        'meta': CategoryCollectionMetaToJSON(value['meta']),
    };
}

