/* tslint:disable */
/* eslint-disable */
/**
 * EasyLog API
 * Programmatic access to EasyLog REST endpoints
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FollowUpEntryUser
 */
export interface FollowUpEntryUser {
    /**
     * 
     * @type {number}
     * @memberof FollowUpEntryUser
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof FollowUpEntryUser
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof FollowUpEntryUser
     */
    email?: string;
}

/**
 * Check if a given object implements the FollowUpEntryUser interface.
 */
export function instanceOfFollowUpEntryUser(value: object): value is FollowUpEntryUser {
    return true;
}

export function FollowUpEntryUserFromJSON(json: any): FollowUpEntryUser {
    return FollowUpEntryUserFromJSONTyped(json, false);
}

export function FollowUpEntryUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): FollowUpEntryUser {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'email': json['email'] == null ? undefined : json['email'],
    };
}

export function FollowUpEntryUserToJSON(json: any): FollowUpEntryUser {
    return FollowUpEntryUserToJSONTyped(json, false);
}

export function FollowUpEntryUserToJSONTyped(value?: FollowUpEntryUser | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'email': value['email'],
    };
}

