/* tslint:disable */
/* eslint-disable */
/**
 * EasyLog API Programmatic access to EasyLog REST endpoints
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
import type { FollowUp } from './FollowUp';
import {
  FollowUpFromJSON,
  FollowUpFromJSONTyped,
  FollowUpToJSON,
  FollowUpToJSONTyped
} from './FollowUp';

/**
 * @export
 * @interface FollowUpResource
 */
export interface FollowUpResource {
  /**
   * @memberof FollowUpResource
   * @type {FollowUp}
   */
  data?: FollowUp;
}

/** Check if a given object implements the FollowUpResource interface. */
export function instanceOfFollowUpResource(
  value: object
): value is FollowUpResource {
  return true;
}

export function FollowUpResourceFromJSON(json: any): FollowUpResource {
  return FollowUpResourceFromJSONTyped(json, false);
}

export function FollowUpResourceFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): FollowUpResource {
  if (json == null) {
    return json;
  }
  return {
    data: json['data'] == null ? undefined : FollowUpFromJSON(json['data'])
  };
}

export function FollowUpResourceToJSON(json: any): FollowUpResource {
  return FollowUpResourceToJSONTyped(json, false);
}

export function FollowUpResourceToJSONTyped(
  value?: FollowUpResource | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    data: FollowUpToJSON(value['data'])
  };
}
