/* tslint:disable */
/* eslint-disable */
/**
 * EasyLog API
 * Programmatic access to EasyLog REST endpoints
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FollowUpEntryUser } from './FollowUpEntryUser';
import {
    FollowUpEntryUserFromJSON,
    FollowUpEntryUserFromJSONTyped,
    FollowUpEntryUserToJSON,
    FollowUpEntryUserToJSONTyped,
} from './FollowUpEntryUser';
import type { FollowUpEntryFollowUp } from './FollowUpEntryFollowUp';
import {
    FollowUpEntryFollowUpFromJSON,
    FollowUpEntryFollowUpFromJSONTyped,
    FollowUpEntryFollowUpToJSON,
    FollowUpEntryFollowUpToJSONTyped,
} from './FollowUpEntryFollowUp';

/**
 * 
 * @export
 * @interface FollowUpEntry
 */
export interface FollowUpEntry {
    /**
     * 
     * @type {number}
     * @memberof FollowUpEntry
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof FollowUpEntry
     */
    followUpId?: number;
    /**
     * 
     * @type {number}
     * @memberof FollowUpEntry
     */
    userId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof FollowUpEntry
     */
    versionId?: number | null;
    /**
     * 
     * @type {object}
     * @memberof FollowUpEntry
     */
    data?: object;
    /**
     * 
     * @type {FollowUpEntryFollowUp}
     * @memberof FollowUpEntry
     */
    followUp?: FollowUpEntryFollowUp;
    /**
     * 
     * @type {FollowUpEntryUser}
     * @memberof FollowUpEntry
     */
    user?: FollowUpEntryUser;
    /**
     * 
     * @type {Date}
     * @memberof FollowUpEntry
     */
    createdAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof FollowUpEntry
     */
    updatedAt?: Date | null;
}

/**
 * Check if a given object implements the FollowUpEntry interface.
 */
export function instanceOfFollowUpEntry(value: object): value is FollowUpEntry {
    return true;
}

export function FollowUpEntryFromJSON(json: any): FollowUpEntry {
    return FollowUpEntryFromJSONTyped(json, false);
}

export function FollowUpEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): FollowUpEntry {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'followUpId': json['follow_up_id'] == null ? undefined : json['follow_up_id'],
        'userId': json['user_id'] == null ? undefined : json['user_id'],
        'versionId': json['version_id'] == null ? undefined : json['version_id'],
        'data': json['data'] == null ? undefined : json['data'],
        'followUp': json['follow_up'] == null ? undefined : FollowUpEntryFollowUpFromJSON(json['follow_up']),
        'user': json['user'] == null ? undefined : FollowUpEntryUserFromJSON(json['user']),
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
    };
}

export function FollowUpEntryToJSON(json: any): FollowUpEntry {
    return FollowUpEntryToJSONTyped(json, false);
}

export function FollowUpEntryToJSONTyped(value?: FollowUpEntry | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'follow_up_id': value['followUpId'],
        'user_id': value['userId'],
        'version_id': value['versionId'],
        'data': value['data'],
        'follow_up': FollowUpEntryFollowUpToJSON(value['followUp']),
        'user': FollowUpEntryUserToJSON(value['user']),
        'created_at': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
    };
}

