/* tslint:disable */
/* eslint-disable */
/**
 * EasyLog API Programmatic access to EasyLog REST endpoints
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
import type { CategoryCollectionLinks } from './CategoryCollectionLinks';
import {
  CategoryCollectionLinksFromJSON,
  CategoryCollectionLinksFromJSONTyped,
  CategoryCollectionLinksToJSON,
  CategoryCollectionLinksToJSONTyped
} from './CategoryCollectionLinks';
import type { CategoryCollectionMeta } from './CategoryCollectionMeta';
import {
  CategoryCollectionMetaFromJSON,
  CategoryCollectionMetaFromJSONTyped,
  CategoryCollectionMetaToJSON,
  CategoryCollectionMetaToJSONTyped
} from './CategoryCollectionMeta';
import type { FollowUpEntry } from './FollowUpEntry';
import {
  FollowUpEntryFromJSON,
  FollowUpEntryFromJSONTyped,
  FollowUpEntryToJSON,
  FollowUpEntryToJSONTyped
} from './FollowUpEntry';

/**
 * Paginated collection of follow-up entries
 *
 * @export
 * @interface FollowUpEntryCollection
 */
export interface FollowUpEntryCollection {
  /**
   * @memberof FollowUpEntryCollection
   * @type {FollowUpEntry[]}
   */
  data?: Array<FollowUpEntry>;
  /**
   * @memberof FollowUpEntryCollection
   * @type {CategoryCollectionLinks}
   */
  links?: CategoryCollectionLinks;
  /**
   * @memberof FollowUpEntryCollection
   * @type {CategoryCollectionMeta}
   */
  meta?: CategoryCollectionMeta;
}

/** Check if a given object implements the FollowUpEntryCollection interface. */
export function instanceOfFollowUpEntryCollection(
  value: object
): value is FollowUpEntryCollection {
  return true;
}

export function FollowUpEntryCollectionFromJSON(
  json: any
): FollowUpEntryCollection {
  return FollowUpEntryCollectionFromJSONTyped(json, false);
}

export function FollowUpEntryCollectionFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): FollowUpEntryCollection {
  if (json == null) {
    return json;
  }
  return {
    data:
      json['data'] == null
        ? undefined
        : (json['data'] as Array<any>).map(FollowUpEntryFromJSON),
    links:
      json['links'] == null
        ? undefined
        : CategoryCollectionLinksFromJSON(json['links']),
    meta:
      json['meta'] == null
        ? undefined
        : CategoryCollectionMetaFromJSON(json['meta'])
  };
}

export function FollowUpEntryCollectionToJSON(
  json: any
): FollowUpEntryCollection {
  return FollowUpEntryCollectionToJSONTyped(json, false);
}

export function FollowUpEntryCollectionToJSONTyped(
  value?: FollowUpEntryCollection | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    data:
      value['data'] == null
        ? undefined
        : (value['data'] as Array<any>).map(FollowUpEntryToJSON),
    links: CategoryCollectionLinksToJSON(value['links']),
    meta: CategoryCollectionMetaToJSON(value['meta'])
  };
}
