/* tslint:disable */
/* eslint-disable */
/**
 * EasyLog API
 * Programmatic access to EasyLog REST endpoints
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FollowUp } from './FollowUp';
import {
    FollowUpFromJSON,
    FollowUpFromJSONTyped,
    FollowUpToJSON,
    FollowUpToJSONTyped,
} from './FollowUp';

/**
 * 
 * @export
 * @interface FollowUpCollection
 */
export interface FollowUpCollection {
    /**
     * 
     * @type {Array<FollowUp>}
     * @memberof FollowUpCollection
     */
    data?: Array<FollowUp>;
}

/**
 * Check if a given object implements the FollowUpCollection interface.
 */
export function instanceOfFollowUpCollection(value: object): value is FollowUpCollection {
    return true;
}

export function FollowUpCollectionFromJSON(json: any): FollowUpCollection {
    return FollowUpCollectionFromJSONTyped(json, false);
}

export function FollowUpCollectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): FollowUpCollection {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(FollowUpFromJSON)),
    };
}

export function FollowUpCollectionToJSON(json: any): FollowUpCollection {
    return FollowUpCollectionToJSONTyped(json, false);
}

export function FollowUpCollectionToJSONTyped(value?: FollowUpCollection | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(FollowUpToJSON)),
    };
}

