/* tslint:disable */
/* eslint-disable */
/**
 * EasyLog API
 * Programmatic access to EasyLog REST endpoints
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FollowUpCategory
 */
export interface FollowUpCategory {
    /**
     * 
     * @type {number}
     * @memberof FollowUpCategory
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof FollowUpCategory
     */
    name?: string;
}

/**
 * Check if a given object implements the FollowUpCategory interface.
 */
export function instanceOfFollowUpCategory(value: object): value is FollowUpCategory {
    return true;
}

export function FollowUpCategoryFromJSON(json: any): FollowUpCategory {
    return FollowUpCategoryFromJSONTyped(json, false);
}

export function FollowUpCategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): FollowUpCategory {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function FollowUpCategoryToJSON(json: any): FollowUpCategory {
    return FollowUpCategoryToJSONTyped(json, false);
}

export function FollowUpCategoryToJSONTyped(value?: FollowUpCategory | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

