/* tslint:disable */
/* eslint-disable */
/**
 * EasyLog API
 * Programmatic access to EasyLog REST endpoints
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FollowUpEntryFollowUp
 */
export interface FollowUpEntryFollowUp {
    /**
     * 
     * @type {number}
     * @memberof FollowUpEntryFollowUp
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof FollowUpEntryFollowUp
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof FollowUpEntryFollowUp
     */
    slug?: string;
}

/**
 * Check if a given object implements the FollowUpEntryFollowUp interface.
 */
export function instanceOfFollowUpEntryFollowUp(value: object): value is FollowUpEntryFollowUp {
    return true;
}

export function FollowUpEntryFollowUpFromJSON(json: any): FollowUpEntryFollowUp {
    return FollowUpEntryFollowUpFromJSONTyped(json, false);
}

export function FollowUpEntryFollowUpFromJSONTyped(json: any, ignoreDiscriminator: boolean): FollowUpEntryFollowUp {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'slug': json['slug'] == null ? undefined : json['slug'],
    };
}

export function FollowUpEntryFollowUpToJSON(json: any): FollowUpEntryFollowUp {
    return FollowUpEntryFollowUpToJSONTyped(json, false);
}

export function FollowUpEntryFollowUpToJSONTyped(value?: FollowUpEntryFollowUp | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'slug': value['slug'],
    };
}

