/* tslint:disable */
/* eslint-disable */
/**
 * EasyLog API Programmatic access to EasyLog REST endpoints
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
/**
 * @export
 * @interface FormListCollectionMeta
 */
export interface FormListCollectionMeta {
  /**
   * @memberof FormListCollectionMeta
   * @type {number}
   */
  currentPage?: number;
  /**
   * @memberof FormListCollectionMeta
   * @type {number}
   */
  from?: number | null;
  /**
   * @memberof FormListCollectionMeta
   * @type {number}
   */
  lastPage?: number;
  /**
   * @memberof FormListCollectionMeta
   * @type {number}
   */
  perPage?: number;
  /**
   * @memberof FormListCollectionMeta
   * @type {number}
   */
  to?: number | null;
  /**
   * @memberof FormListCollectionMeta
   * @type {number}
   */
  total?: number;
}

/** Check if a given object implements the FormListCollectionMeta interface. */
export function instanceOfFormListCollectionMeta(
  value: object
): value is FormListCollectionMeta {
  return true;
}

export function FormListCollectionMetaFromJSON(
  json: any
): FormListCollectionMeta {
  return FormListCollectionMetaFromJSONTyped(json, false);
}

export function FormListCollectionMetaFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): FormListCollectionMeta {
  if (json == null) {
    return json;
  }
  return {
    currentPage:
      json['current_page'] == null ? undefined : json['current_page'],
    from: json['from'] == null ? undefined : json['from'],
    lastPage: json['last_page'] == null ? undefined : json['last_page'],
    perPage: json['per_page'] == null ? undefined : json['per_page'],
    to: json['to'] == null ? undefined : json['to'],
    total: json['total'] == null ? undefined : json['total']
  };
}

export function FormListCollectionMetaToJSON(
  json: any
): FormListCollectionMeta {
  return FormListCollectionMetaToJSONTyped(json, false);
}

export function FormListCollectionMetaToJSONTyped(
  value?: FormListCollectionMeta | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    current_page: value['currentPage'],
    from: value['from'],
    last_page: value['lastPage'],
    per_page: value['perPage'],
    to: value['to'],
    total: value['total']
  };
}
