/* tslint:disable */
/* eslint-disable */
/**
 * EasyLog API Programmatic access to EasyLog REST endpoints
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
import type { CategoryCollectionLinks } from './CategoryCollectionLinks';
import {
  CategoryCollectionLinksFromJSON,
  CategoryCollectionLinksFromJSONTyped,
  CategoryCollectionLinksToJSON,
  CategoryCollectionLinksToJSONTyped
} from './CategoryCollectionLinks';
import type { CategoryCollectionMeta } from './CategoryCollectionMeta';
import {
  CategoryCollectionMetaFromJSON,
  CategoryCollectionMetaFromJSONTyped,
  CategoryCollectionMetaToJSON,
  CategoryCollectionMetaToJSONTyped
} from './CategoryCollectionMeta';
import type { FormListItem } from './FormListItem';
import {
  FormListItemFromJSON,
  FormListItemFromJSONTyped,
  FormListItemToJSON,
  FormListItemToJSONTyped
} from './FormListItem';

/**
 * @export
 * @interface FormListCollection
 */
export interface FormListCollection {
  /**
   * @memberof FormListCollection
   * @type {FormListItem[]}
   */
  data?: Array<FormListItem>;
  /**
   * @memberof FormListCollection
   * @type {CategoryCollectionLinks}
   */
  links?: CategoryCollectionLinks;
  /**
   * @memberof FormListCollection
   * @type {CategoryCollectionMeta}
   */
  meta?: CategoryCollectionMeta;
}

/** Check if a given object implements the FormListCollection interface. */
export function instanceOfFormListCollection(
  value: object
): value is FormListCollection {
  return true;
}

export function FormListCollectionFromJSON(json: any): FormListCollection {
  return FormListCollectionFromJSONTyped(json, false);
}

export function FormListCollectionFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): FormListCollection {
  if (json == null) {
    return json;
  }
  return {
    data:
      json['data'] == null
        ? undefined
        : (json['data'] as Array<any>).map(FormListItemFromJSON),
    links:
      json['links'] == null
        ? undefined
        : CategoryCollectionLinksFromJSON(json['links']),
    meta:
      json['meta'] == null
        ? undefined
        : CategoryCollectionMetaFromJSON(json['meta'])
  };
}

export function FormListCollectionToJSON(json: any): FormListCollection {
  return FormListCollectionToJSONTyped(json, false);
}

export function FormListCollectionToJSONTyped(
  value?: FormListCollection | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    data:
      value['data'] == null
        ? undefined
        : (value['data'] as Array<any>).map(FormListItemToJSON),
    links: CategoryCollectionLinksToJSON(value['links']),
    meta: CategoryCollectionMetaToJSON(value['meta'])
  };
}
