/* tslint:disable */
/* eslint-disable */
/**
 * EasyLog API Programmatic access to EasyLog REST endpoints
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Lightweight form representation for list endpoints
 *
 * @export
 * @interface FormListItem
 */
export interface FormListItem {
  /**
   * @memberof FormListItem
   * @type {number}
   */
  id?: number;
  /**
   * @memberof FormListItem
   * @type {string}
   */
  name?: string;
  /**
   * @memberof FormListItem
   * @type {string}
   */
  description?: string | null;
  /**
   * @memberof FormListItem
   * @type {string}
   */
  avatar?: string | null;
  /**
   * @memberof FormListItem
   * @type {number}
   */
  clientId?: number;
  /**
   * @memberof FormListItem
   * @type {boolean}
   */
  hasActions?: boolean;
  /**
   * @memberof FormListItem
   * @type {Date}
   */
  createdAt?: Date | null;
  /**
   * @memberof FormListItem
   * @type {Date}
   */
  updatedAt?: Date | null;
  /**
   * @memberof FormListItem
   * @type {Date}
   */
  accessedAt?: Date | null;
}

/** Check if a given object implements the FormListItem interface. */
export function instanceOfFormListItem(value: object): value is FormListItem {
  return true;
}

export function FormListItemFromJSON(json: any): FormListItem {
  return FormListItemFromJSONTyped(json, false);
}

export function FormListItemFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): FormListItem {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'] == null ? undefined : json['id'],
    name: json['name'] == null ? undefined : json['name'],
    description: json['description'] == null ? undefined : json['description'],
    avatar: json['avatar'] == null ? undefined : json['avatar'],
    clientId: json['client_id'] == null ? undefined : json['client_id'],
    hasActions: json['has_actions'] == null ? undefined : json['has_actions'],
    createdAt:
      json['created_at'] == null ? undefined : new Date(json['created_at']),
    updatedAt:
      json['updated_at'] == null ? undefined : new Date(json['updated_at']),
    accessedAt:
      json['accessed_at'] == null ? undefined : new Date(json['accessed_at'])
  };
}

export function FormListItemToJSON(json: any): FormListItem {
  return FormListItemToJSONTyped(json, false);
}

export function FormListItemToJSONTyped(
  value?: FormListItem | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    name: value['name'],
    description: value['description'],
    avatar: value['avatar'],
    client_id: value['clientId'],
    has_actions: value['hasActions'],
    created_at:
      value['createdAt'] == null
        ? undefined
        : (value['createdAt'] as any).toISOString(),
    updated_at:
      value['updatedAt'] == null
        ? undefined
        : (value['updatedAt'] as any).toISOString(),
    accessed_at:
      value['accessedAt'] == null
        ? undefined
        : (value['accessedAt'] as any).toISOString()
  };
}
