/* tslint:disable */
/* eslint-disable */
/**
 * EasyLog API
 * Programmatic access to EasyLog REST endpoints
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FormListItem } from './FormListItem';
import {
    FormListItemFromJSON,
    FormListItemFromJSONTyped,
    FormListItemToJSON,
    FormListItemToJSONTyped,
} from './FormListItem';

/**
 * 
 * @export
 * @interface FormListResource
 */
export interface FormListResource {
    /**
     * 
     * @type {FormListItem}
     * @memberof FormListResource
     */
    data?: FormListItem;
}

/**
 * Check if a given object implements the FormListResource interface.
 */
export function instanceOfFormListResource(value: object): value is FormListResource {
    return true;
}

export function FormListResourceFromJSON(json: any): FormListResource {
    return FormListResourceFromJSONTyped(json, false);
}

export function FormListResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): FormListResource {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : FormListItemFromJSON(json['data']),
    };
}

export function FormListResourceToJSON(json: any): FormListResource {
    return FormListResourceToJSONTyped(json, false);
}

export function FormListResourceToJSONTyped(value?: FormListResource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': FormListItemToJSON(value['data']),
    };
}

