/* tslint:disable */
/* eslint-disable */
/**
 * EasyLog API Programmatic access to EasyLog REST endpoints
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
/**
 * @export
 * @interface FormListCollectionLinks
 */
export interface FormListCollectionLinks {
  /**
   * @memberof FormListCollectionLinks
   * @type {string}
   */
  first?: string | null;
  /**
   * @memberof FormListCollectionLinks
   * @type {string}
   */
  last?: string | null;
  /**
   * @memberof FormListCollectionLinks
   * @type {string}
   */
  prev?: string | null;
  /**
   * @memberof FormListCollectionLinks
   * @type {string}
   */
  next?: string | null;
}

/** Check if a given object implements the FormListCollectionLinks interface. */
export function instanceOfFormListCollectionLinks(
  value: object
): value is FormListCollectionLinks {
  return true;
}

export function FormListCollectionLinksFromJSON(
  json: any
): FormListCollectionLinks {
  return FormListCollectionLinksFromJSONTyped(json, false);
}

export function FormListCollectionLinksFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): FormListCollectionLinks {
  if (json == null) {
    return json;
  }
  return {
    first: json['first'] == null ? undefined : json['first'],
    last: json['last'] == null ? undefined : json['last'],
    prev: json['prev'] == null ? undefined : json['prev'],
    next: json['next'] == null ? undefined : json['next']
  };
}

export function FormListCollectionLinksToJSON(
  json: any
): FormListCollectionLinks {
  return FormListCollectionLinksToJSONTyped(json, false);
}

export function FormListCollectionLinksToJSONTyped(
  value?: FormListCollectionLinks | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    first: value['first'],
    last: value['last'],
    prev: value['prev'],
    next: value['next']
  };
}
