/* tslint:disable */
/* eslint-disable */
/**
 * EasyLog API
 * Programmatic access to EasyLog REST endpoints
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Form } from './Form';
import {
    FormFromJSON,
    FormFromJSONTyped,
    FormToJSON,
    FormToJSONTyped,
} from './Form';

/**
 * 
 * @export
 * @interface FormResource
 */
export interface FormResource {
    /**
     * 
     * @type {Form}
     * @memberof FormResource
     */
    data?: Form;
}

/**
 * Check if a given object implements the FormResource interface.
 */
export function instanceOfFormResource(value: object): value is FormResource {
    return true;
}

export function FormResourceFromJSON(json: any): FormResource {
    return FormResourceFromJSONTyped(json, false);
}

export function FormResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): FormResource {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : FormFromJSON(json['data']),
    };
}

export function FormResourceToJSON(json: any): FormResource {
    return FormResourceToJSONTyped(json, false);
}

export function FormResourceToJSONTyped(value?: FormResource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': FormToJSON(value['data']),
    };
}

