/* tslint:disable */
/* eslint-disable */
/**
 * EasyLog API
 * Programmatic access to EasyLog REST endpoints
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Form } from './Form';
import {
    FormFromJSON,
    FormFromJSONTyped,
    FormToJSON,
    FormToJSONTyped,
} from './Form';

/**
 * 
 * @export
 * @interface FormCollection
 */
export interface FormCollection {
    /**
     * 
     * @type {Array<Form>}
     * @memberof FormCollection
     */
    data?: Array<Form>;
}

/**
 * Check if a given object implements the FormCollection interface.
 */
export function instanceOfFormCollection(value: object): value is FormCollection {
    return true;
}

export function FormCollectionFromJSON(json: any): FormCollection {
    return FormCollectionFromJSONTyped(json, false);
}

export function FormCollectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): FormCollection {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(FormFromJSON)),
    };
}

export function FormCollectionToJSON(json: any): FormCollection {
    return FormCollectionToJSONTyped(json, false);
}

export function FormCollectionToJSONTyped(value?: FormCollection | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(FormToJSON)),
    };
}

