/* tslint:disable */
/* eslint-disable */
/**
 * EasyLog API Programmatic access to EasyLog REST endpoints
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
import type { MediaResource } from './MediaResource';
import {
  MediaResourceFromJSON,
  MediaResourceFromJSONTyped,
  MediaResourceToJSON,
  MediaResourceToJSONTyped
} from './MediaResource';

/**
 * @export
 * @interface ListFollowUpEntryMedia200Response
 */
export interface ListFollowUpEntryMedia200Response {
  /**
   * @memberof ListFollowUpEntryMedia200Response
   * @type {MediaResource[]}
   */
  data?: Array<MediaResource>;
}

/**
 * Check if a given object implements the ListFollowUpEntryMedia200Response
 * interface.
 */
export function instanceOfListFollowUpEntryMedia200Response(
  value: object
): value is ListFollowUpEntryMedia200Response {
  return true;
}

export function ListFollowUpEntryMedia200ResponseFromJSON(
  json: any
): ListFollowUpEntryMedia200Response {
  return ListFollowUpEntryMedia200ResponseFromJSONTyped(json, false);
}

export function ListFollowUpEntryMedia200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ListFollowUpEntryMedia200Response {
  if (json == null) {
    return json;
  }
  return {
    data:
      json['data'] == null
        ? undefined
        : (json['data'] as Array<any>).map(MediaResourceFromJSON)
  };
}

export function ListFollowUpEntryMedia200ResponseToJSON(
  json: any
): ListFollowUpEntryMedia200Response {
  return ListFollowUpEntryMedia200ResponseToJSONTyped(json, false);
}

export function ListFollowUpEntryMedia200ResponseToJSONTyped(
  value?: ListFollowUpEntryMedia200Response | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    data:
      value['data'] == null
        ? undefined
        : (value['data'] as Array<any>).map(MediaResourceToJSON)
  };
}
