/* tslint:disable */
/* eslint-disable */
/**
 * EasyLog API
 * Programmatic access to EasyLog REST endpoints
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MediaResource } from './MediaResource';
import {
    MediaResourceFromJSON,
    MediaResourceFromJSONTyped,
    MediaResourceToJSON,
    MediaResourceToJSONTyped,
} from './MediaResource';

/**
 * 
 * @export
 * @interface ListSubmissionMedia200Response
 */
export interface ListSubmissionMedia200Response {
    /**
     * 
     * @type {Array<MediaResource>}
     * @memberof ListSubmissionMedia200Response
     */
    data?: Array<MediaResource>;
}

/**
 * Check if a given object implements the ListSubmissionMedia200Response interface.
 */
export function instanceOfListSubmissionMedia200Response(value: object): value is ListSubmissionMedia200Response {
    return true;
}

export function ListSubmissionMedia200ResponseFromJSON(json: any): ListSubmissionMedia200Response {
    return ListSubmissionMedia200ResponseFromJSONTyped(json, false);
}

export function ListSubmissionMedia200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListSubmissionMedia200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(MediaResourceFromJSON)),
    };
}

export function ListSubmissionMedia200ResponseToJSON(json: any): ListSubmissionMedia200Response {
    return ListSubmissionMedia200ResponseToJSONTyped(json, false);
}

export function ListSubmissionMedia200ResponseToJSONTyped(value?: ListSubmissionMedia200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(MediaResourceToJSON)),
    };
}

