/* tslint:disable */
/* eslint-disable */
/**
 * EasyLog API
 * Programmatic access to EasyLog REST endpoints
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Available image conversions with presigned URLs
 * @export
 * @interface MediaDetailResourceConversions
 */
export interface MediaDetailResourceConversions {
    /**
     * 150x150px thumbnail
     * @type {string}
     * @memberof MediaDetailResourceConversions
     */
    preview?: string;
    /**
     * 550px height
     * @type {string}
     * @memberof MediaDetailResourceConversions
     */
    detail?: string;
    /**
     * 
     * @type {string}
     * @memberof MediaDetailResourceConversions
     */
    maxHeight300px?: string;
    /**
     * 
     * @type {string}
     * @memberof MediaDetailResourceConversions
     */
    maxHeight380px?: string;
    /**
     * 
     * @type {string}
     * @memberof MediaDetailResourceConversions
     */
    maxHeight850px?: string;
    /**
     * 
     * @type {string}
     * @memberof MediaDetailResourceConversions
     */
    maxHeight1000px?: string;
}

/**
 * Check if a given object implements the MediaDetailResourceConversions interface.
 */
export function instanceOfMediaDetailResourceConversions(value: object): value is MediaDetailResourceConversions {
    return true;
}

export function MediaDetailResourceConversionsFromJSON(json: any): MediaDetailResourceConversions {
    return MediaDetailResourceConversionsFromJSONTyped(json, false);
}

export function MediaDetailResourceConversionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): MediaDetailResourceConversions {
    if (json == null) {
        return json;
    }
    return {
        
        'preview': json['preview'] == null ? undefined : json['preview'],
        'detail': json['detail'] == null ? undefined : json['detail'],
        'maxHeight300px': json['max-height-300px'] == null ? undefined : json['max-height-300px'],
        'maxHeight380px': json['max-height-380px'] == null ? undefined : json['max-height-380px'],
        'maxHeight850px': json['max-height-850px'] == null ? undefined : json['max-height-850px'],
        'maxHeight1000px': json['max-height-1000px'] == null ? undefined : json['max-height-1000px'],
    };
}

export function MediaDetailResourceConversionsToJSON(json: any): MediaDetailResourceConversions {
    return MediaDetailResourceConversionsToJSONTyped(json, false);
}

export function MediaDetailResourceConversionsToJSONTyped(value?: MediaDetailResourceConversions | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'preview': value['preview'],
        'detail': value['detail'],
        'max-height-300px': value['maxHeight300px'],
        'max-height-380px': value['maxHeight380px'],
        'max-height-850px': value['maxHeight850px'],
        'max-height-1000px': value['maxHeight1000px'],
    };
}

