/* tslint:disable */
/* eslint-disable */
/**
 * EasyLog API Programmatic access to EasyLog REST endpoints
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
/**
 * @export
 * @interface MediaDetailResourceDimensions
 */
export interface MediaDetailResourceDimensions {
  /**
   * @memberof MediaDetailResourceDimensions
   * @type {number}
   */
  width?: number | null;
  /**
   * @memberof MediaDetailResourceDimensions
   * @type {number}
   */
  height?: number | null;
}

/**
 * Check if a given object implements the MediaDetailResourceDimensions
 * interface.
 */
export function instanceOfMediaDetailResourceDimensions(
  value: object
): value is MediaDetailResourceDimensions {
  return true;
}

export function MediaDetailResourceDimensionsFromJSON(
  json: any
): MediaDetailResourceDimensions {
  return MediaDetailResourceDimensionsFromJSONTyped(json, false);
}

export function MediaDetailResourceDimensionsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): MediaDetailResourceDimensions {
  if (json == null) {
    return json;
  }
  return {
    width: json['width'] == null ? undefined : json['width'],
    height: json['height'] == null ? undefined : json['height']
  };
}

export function MediaDetailResourceDimensionsToJSON(
  json: any
): MediaDetailResourceDimensions {
  return MediaDetailResourceDimensionsToJSONTyped(json, false);
}

export function MediaDetailResourceDimensionsToJSONTyped(
  value?: MediaDetailResourceDimensions | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    width: value['width'],
    height: value['height']
  };
}
