/* tslint:disable */
/* eslint-disable */
/**
 * EasyLog API
 * Programmatic access to EasyLog REST endpoints
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Entity } from './Entity';
import {
    EntityFromJSON,
    EntityFromJSONTyped,
    EntityToJSON,
    EntityToJSONTyped,
} from './Entity';

/**
 * 
 * @export
 * @interface Model2e63ab79cdb720663c3edf47fee45c62200Response
 */
export interface Model2e63ab79cdb720663c3edf47fee45c62200Response {
    /**
     * 
     * @type {Entity}
     * @memberof Model2e63ab79cdb720663c3edf47fee45c62200Response
     */
    data: Entity;
}

/**
 * Check if a given object implements the Model2e63ab79cdb720663c3edf47fee45c62200Response interface.
 */
export function instanceOfModel2e63ab79cdb720663c3edf47fee45c62200Response(value: object): value is Model2e63ab79cdb720663c3edf47fee45c62200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function Model2e63ab79cdb720663c3edf47fee45c62200ResponseFromJSON(json: any): Model2e63ab79cdb720663c3edf47fee45c62200Response {
    return Model2e63ab79cdb720663c3edf47fee45c62200ResponseFromJSONTyped(json, false);
}

export function Model2e63ab79cdb720663c3edf47fee45c62200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Model2e63ab79cdb720663c3edf47fee45c62200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': EntityFromJSON(json['data']),
    };
}

export function Model2e63ab79cdb720663c3edf47fee45c62200ResponseToJSON(json: any): Model2e63ab79cdb720663c3edf47fee45c62200Response {
    return Model2e63ab79cdb720663c3edf47fee45c62200ResponseToJSONTyped(json, false);
}

export function Model2e63ab79cdb720663c3edf47fee45c62200ResponseToJSONTyped(value?: Model2e63ab79cdb720663c3edf47fee45c62200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': EntityToJSON(value['data']),
    };
}

