/* tslint:disable */
/* eslint-disable */
/**
 * EasyLog API Programmatic access to EasyLog REST endpoints
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
import type { Resource } from './Resource';
import {
  ResourceFromJSON,
  ResourceFromJSONTyped,
  ResourceToJSON,
  ResourceToJSONTyped
} from './Resource';

/**
 * @export
 * @interface Model1fc1206aaba89a63335ac7991e0f5cc3200Response
 */
export interface Model1fc1206aaba89a63335ac7991e0f5cc3200Response {
  /**
   * @memberof Model1fc1206aaba89a63335ac7991e0f5cc3200Response
   * @type {Resource}
   */
  data: Resource;
}

/**
 * Check if a given object implements the
 * Model1fc1206aaba89a63335ac7991e0f5cc3200Response interface.
 */
export function instanceOfModel1fc1206aaba89a63335ac7991e0f5cc3200Response(
  value: object
): value is Model1fc1206aaba89a63335ac7991e0f5cc3200Response {
  if (!('data' in value) || value['data'] === undefined) return false;
  return true;
}

export function Model1fc1206aaba89a63335ac7991e0f5cc3200ResponseFromJSON(
  json: any
): Model1fc1206aaba89a63335ac7991e0f5cc3200Response {
  return Model1fc1206aaba89a63335ac7991e0f5cc3200ResponseFromJSONTyped(
    json,
    false
  );
}

export function Model1fc1206aaba89a63335ac7991e0f5cc3200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): Model1fc1206aaba89a63335ac7991e0f5cc3200Response {
  if (json == null) {
    return json;
  }
  return {
    data: ResourceFromJSON(json['data'])
  };
}

export function Model1fc1206aaba89a63335ac7991e0f5cc3200ResponseToJSON(
  json: any
): Model1fc1206aaba89a63335ac7991e0f5cc3200Response {
  return Model1fc1206aaba89a63335ac7991e0f5cc3200ResponseToJSONTyped(
    json,
    false
  );
}

export function Model1fc1206aaba89a63335ac7991e0f5cc3200ResponseToJSONTyped(
  value?: Model1fc1206aaba89a63335ac7991e0f5cc3200Response | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    data: ResourceToJSON(value['data'])
  };
}
