/* tslint:disable */
/* eslint-disable */
/**
 * EasyLog API Programmatic access to EasyLog REST endpoints
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
/**
 * @export
 * @interface PaginationLink
 */
export interface PaginationLink {
  /**
   * @memberof PaginationLink
   * @type {string}
   */
  url?: string | null;
  /**
   * @memberof PaginationLink
   * @type {string}
   */
  label?: string;
  /**
   * @memberof PaginationLink
   * @type {boolean}
   */
  active?: boolean;
}

/** Check if a given object implements the PaginationLink interface. */
export function instanceOfPaginationLink(
  value: object
): value is PaginationLink {
  return true;
}

export function PaginationLinkFromJSON(json: any): PaginationLink {
  return PaginationLinkFromJSONTyped(json, false);
}

export function PaginationLinkFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): PaginationLink {
  if (json == null) {
    return json;
  }
  return {
    url: json['url'] == null ? undefined : json['url'],
    label: json['label'] == null ? undefined : json['label'],
    active: json['active'] == null ? undefined : json['active']
  };
}

export function PaginationLinkToJSON(json: any): PaginationLink {
  return PaginationLinkToJSONTyped(json, false);
}

export function PaginationLinkToJSONTyped(
  value?: PaginationLink | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    url: value['url'],
    label: value['label'],
    active: value['active']
  };
}
