/* tslint:disable */
/* eslint-disable */
/**
 * EasyLog API
 * Programmatic access to EasyLog REST endpoints
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaginationLinks
 */
export interface PaginationLinks {
    /**
     * 
     * @type {string}
     * @memberof PaginationLinks
     */
    first?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginationLinks
     */
    last?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginationLinks
     */
    prev?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginationLinks
     */
    next?: string | null;
}

/**
 * Check if a given object implements the PaginationLinks interface.
 */
export function instanceOfPaginationLinks(value: object): value is PaginationLinks {
    return true;
}

export function PaginationLinksFromJSON(json: any): PaginationLinks {
    return PaginationLinksFromJSONTyped(json, false);
}

export function PaginationLinksFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginationLinks {
    if (json == null) {
        return json;
    }
    return {
        
        'first': json['first'] == null ? undefined : json['first'],
        'last': json['last'] == null ? undefined : json['last'],
        'prev': json['prev'] == null ? undefined : json['prev'],
        'next': json['next'] == null ? undefined : json['next'],
    };
}

export function PaginationLinksToJSON(json: any): PaginationLinks {
    return PaginationLinksToJSONTyped(json, false);
}

export function PaginationLinksToJSONTyped(value?: PaginationLinks | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'first': value['first'],
        'last': value['last'],
        'prev': value['prev'],
        'next': value['next'],
    };
}

