/* tslint:disable */
/* eslint-disable */
/**
 * EasyLog API Programmatic access to EasyLog REST endpoints
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginationLink } from './PaginationLink';
import {
  PaginationLinkFromJSON,
  PaginationLinkFromJSONTyped,
  PaginationLinkToJSON,
  PaginationLinkToJSONTyped
} from './PaginationLink';

/**
 * @export
 * @interface PaginationMeta
 */
export interface PaginationMeta {
  /**
   * @memberof PaginationMeta
   * @type {number}
   */
  currentPage: number;
  /**
   * @memberof PaginationMeta
   * @type {number}
   */
  from?: number | null;
  /**
   * @memberof PaginationMeta
   * @type {number}
   */
  lastPage?: number;
  /**
   * @memberof PaginationMeta
   * @type {PaginationLink[]}
   */
  links?: Array<PaginationLink>;
  /**
   * @memberof PaginationMeta
   * @type {string}
   */
  path?: string;
  /**
   * @memberof PaginationMeta
   * @type {number}
   */
  perPage: number;
  /**
   * @memberof PaginationMeta
   * @type {number}
   */
  to?: number | null;
  /**
   * @memberof PaginationMeta
   * @type {number}
   */
  total: number;
}

/** Check if a given object implements the PaginationMeta interface. */
export function instanceOfPaginationMeta(
  value: object
): value is PaginationMeta {
  if (!('currentPage' in value) || value['currentPage'] === undefined)
    return false;
  if (!('perPage' in value) || value['perPage'] === undefined) return false;
  if (!('total' in value) || value['total'] === undefined) return false;
  return true;
}

export function PaginationMetaFromJSON(json: any): PaginationMeta {
  return PaginationMetaFromJSONTyped(json, false);
}

export function PaginationMetaFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): PaginationMeta {
  if (json == null) {
    return json;
  }
  return {
    currentPage: json['current_page'],
    from: json['from'] == null ? undefined : json['from'],
    lastPage: json['last_page'] == null ? undefined : json['last_page'],
    links:
      json['links'] == null
        ? undefined
        : (json['links'] as Array<any>).map(PaginationLinkFromJSON),
    path: json['path'] == null ? undefined : json['path'],
    perPage: json['per_page'],
    to: json['to'] == null ? undefined : json['to'],
    total: json['total']
  };
}

export function PaginationMetaToJSON(json: any): PaginationMeta {
  return PaginationMetaToJSONTyped(json, false);
}

export function PaginationMetaToJSONTyped(
  value?: PaginationMeta | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    current_page: value['currentPage'],
    from: value['from'],
    last_page: value['lastPage'],
    links:
      value['links'] == null
        ? undefined
        : (value['links'] as Array<any>).map(PaginationLinkToJSON),
    path: value['path'],
    per_page: value['perPage'],
    to: value['to'],
    total: value['total']
  };
}
