/* tslint:disable */
/* eslint-disable */
/**
 * EasyLog API Programmatic access to EasyLog REST endpoints
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
/**
 * @export
 * @interface PersistSubmission201Response
 */
export interface PersistSubmission201Response {
  /**
   * @memberof PersistSubmission201Response
   * @type {number}
   */
  submissionId?: number;
  /**
   * @memberof PersistSubmission201Response
   * @type {boolean}
   */
  success?: boolean;
}

/**
 * Check if a given object implements the PersistSubmission201Response
 * interface.
 */
export function instanceOfPersistSubmission201Response(
  value: object
): value is PersistSubmission201Response {
  return true;
}

export function PersistSubmission201ResponseFromJSON(
  json: any
): PersistSubmission201Response {
  return PersistSubmission201ResponseFromJSONTyped(json, false);
}

export function PersistSubmission201ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): PersistSubmission201Response {
  if (json == null) {
    return json;
  }
  return {
    submissionId:
      json['submission_id'] == null ? undefined : json['submission_id'],
    success: json['success'] == null ? undefined : json['success']
  };
}

export function PersistSubmission201ResponseToJSON(
  json: any
): PersistSubmission201Response {
  return PersistSubmission201ResponseToJSONTyped(json, false);
}

export function PersistSubmission201ResponseToJSONTyped(
  value?: PersistSubmission201Response | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    submission_id: value['submissionId'],
    success: value['success']
  };
}
