/* tslint:disable */
/* eslint-disable */
/**
 * EasyLog API
 * Programmatic access to EasyLog REST endpoints
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PersistSubmissionRequest
 */
export interface PersistSubmissionRequest {
    /**
     * Form submission data
     * @type {{ [key: string]: any; }}
     * @memberof PersistSubmissionRequest
     */
    data: { [key: string]: any; };
    /**
     * Form version ID
     * @type {number}
     * @memberof PersistSubmissionRequest
     */
    formVersionId: number;
    /**
     * Optional checksum for validation
     * @type {string}
     * @memberof PersistSubmissionRequest
     */
    checksum?: string;
}

/**
 * Check if a given object implements the PersistSubmissionRequest interface.
 */
export function instanceOfPersistSubmissionRequest(value: object): value is PersistSubmissionRequest {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('formVersionId' in value) || value['formVersionId'] === undefined) return false;
    return true;
}

export function PersistSubmissionRequestFromJSON(json: any): PersistSubmissionRequest {
    return PersistSubmissionRequestFromJSONTyped(json, false);
}

export function PersistSubmissionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PersistSubmissionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'],
        'formVersionId': json['form_version_id'],
        'checksum': json['checksum'] == null ? undefined : json['checksum'],
    };
}

export function PersistSubmissionRequestToJSON(json: any): PersistSubmissionRequest {
    return PersistSubmissionRequestToJSONTyped(json, false);
}

export function PersistSubmissionRequestToJSONTyped(value?: PersistSubmissionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'],
        'form_version_id': value['formVersionId'],
        'checksum': value['checksum'],
    };
}

