/* tslint:disable */
/* eslint-disable */
/**
 * EasyLog API Programmatic access to EasyLog REST endpoints
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
/**
 * @export
 * @interface PhaseUpdatePayload
 */
export interface PhaseUpdatePayload {
  /**
   * @memberof PhaseUpdatePayload
   * @type {Date}
   */
  start: Date;
  /**
   * @memberof PhaseUpdatePayload
   * @type {Date}
   */
  end: Date;
  /**
   * @memberof PhaseUpdatePayload
   * @type {boolean}
   */
  isStaged?: boolean | null;
}

/** Check if a given object implements the PhaseUpdatePayload interface. */
export function instanceOfPhaseUpdatePayload(
  value: object
): value is PhaseUpdatePayload {
  if (!('start' in value) || value['start'] === undefined) return false;
  if (!('end' in value) || value['end'] === undefined) return false;
  return true;
}

export function PhaseUpdatePayloadFromJSON(json: any): PhaseUpdatePayload {
  return PhaseUpdatePayloadFromJSONTyped(json, false);
}

export function PhaseUpdatePayloadFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): PhaseUpdatePayload {
  if (json == null) {
    return json;
  }
  return {
    start: new Date(json['start']),
    end: new Date(json['end']),
    isStaged: json['is_staged'] == null ? undefined : json['is_staged']
  };
}

export function PhaseUpdatePayloadToJSON(json: any): PhaseUpdatePayload {
  return PhaseUpdatePayloadToJSONTyped(json, false);
}

export function PhaseUpdatePayloadToJSONTyped(
  value?: PhaseUpdatePayload | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    start: value['start'].toISOString(),
    end: value['end'].toISOString(),
    is_staged: value['isStaged']
  };
}
