/* tslint:disable */
/* eslint-disable */
/**
 * EasyLog API
 * Programmatic access to EasyLog REST endpoints
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Phase
 */
export interface Phase {
    /**
     * 
     * @type {number}
     * @memberof Phase
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Phase
     */
    slug: string;
    /**
     * 
     * @type {Date}
     * @memberof Phase
     */
    start: Date;
    /**
     * 
     * @type {Date}
     * @memberof Phase
     */
    end: Date;
    /**
     * 
     * @type {boolean}
     * @memberof Phase
     */
    isStaged?: boolean;
}

/**
 * Check if a given object implements the Phase interface.
 */
export function instanceOfPhase(value: object): value is Phase {
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('start' in value) || value['start'] === undefined) return false;
    if (!('end' in value) || value['end'] === undefined) return false;
    return true;
}

export function PhaseFromJSON(json: any): Phase {
    return PhaseFromJSONTyped(json, false);
}

export function PhaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Phase {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'slug': json['slug'],
        'start': (new Date(json['start'])),
        'end': (new Date(json['end'])),
        'isStaged': json['is_staged'] == null ? undefined : json['is_staged'],
    };
}

export function PhaseToJSON(json: any): Phase {
    return PhaseToJSONTyped(json, false);
}

export function PhaseToJSONTyped(value?: Phase | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'slug': value['slug'],
        'start': ((value['start']).toISOString()),
        'end': ((value['end']).toISOString()),
        'is_staged': value['isStaged'],
    };
}

