/* tslint:disable */
/* eslint-disable */
/**
 * EasyLog API
 * Programmatic access to EasyLog REST endpoints
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PhaseCreatePayload
 */
export interface PhaseCreatePayload {
    /**
     * 
     * @type {string}
     * @memberof PhaseCreatePayload
     */
    slug: string;
    /**
     * 
     * @type {Date}
     * @memberof PhaseCreatePayload
     */
    start: Date;
    /**
     * 
     * @type {Date}
     * @memberof PhaseCreatePayload
     */
    end: Date;
    /**
     * 
     * @type {boolean}
     * @memberof PhaseCreatePayload
     */
    isStaged?: boolean | null;
}

/**
 * Check if a given object implements the PhaseCreatePayload interface.
 */
export function instanceOfPhaseCreatePayload(value: object): value is PhaseCreatePayload {
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('start' in value) || value['start'] === undefined) return false;
    if (!('end' in value) || value['end'] === undefined) return false;
    return true;
}

export function PhaseCreatePayloadFromJSON(json: any): PhaseCreatePayload {
    return PhaseCreatePayloadFromJSONTyped(json, false);
}

export function PhaseCreatePayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): PhaseCreatePayload {
    if (json == null) {
        return json;
    }
    return {
        
        'slug': json['slug'],
        'start': (new Date(json['start'])),
        'end': (new Date(json['end'])),
        'isStaged': json['is_staged'] == null ? undefined : json['is_staged'],
    };
}

export function PhaseCreatePayloadToJSON(json: any): PhaseCreatePayload {
    return PhaseCreatePayloadToJSONTyped(json, false);
}

export function PhaseCreatePayloadToJSONTyped(value?: PhaseCreatePayload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'slug': value['slug'],
        'start': ((value['start']).toISOString()),
        'end': ((value['end']).toISOString()),
        'is_staged': value['isStaged'],
    };
}

