/* tslint:disable */
/* eslint-disable */
/**
 * EasyLog API
 * Programmatic access to EasyLog REST endpoints
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PrepareSubmission200ResponseFilesInner } from './PrepareSubmission200ResponseFilesInner';
import {
    PrepareSubmission200ResponseFilesInnerFromJSON,
    PrepareSubmission200ResponseFilesInnerFromJSONTyped,
    PrepareSubmission200ResponseFilesInnerToJSON,
    PrepareSubmission200ResponseFilesInnerToJSONTyped,
} from './PrepareSubmission200ResponseFilesInner';

/**
 * 
 * @export
 * @interface PrepareSubmission200Response
 */
export interface PrepareSubmission200Response {
    /**
     * 
     * @type {Array<PrepareSubmission200ResponseFilesInner>}
     * @memberof PrepareSubmission200Response
     */
    files?: Array<PrepareSubmission200ResponseFilesInner>;
}

/**
 * Check if a given object implements the PrepareSubmission200Response interface.
 */
export function instanceOfPrepareSubmission200Response(value: object): value is PrepareSubmission200Response {
    return true;
}

export function PrepareSubmission200ResponseFromJSON(json: any): PrepareSubmission200Response {
    return PrepareSubmission200ResponseFromJSONTyped(json, false);
}

export function PrepareSubmission200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PrepareSubmission200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'files': json['files'] == null ? undefined : ((json['files'] as Array<any>).map(PrepareSubmission200ResponseFilesInnerFromJSON)),
    };
}

export function PrepareSubmission200ResponseToJSON(json: any): PrepareSubmission200Response {
    return PrepareSubmission200ResponseToJSONTyped(json, false);
}

export function PrepareSubmission200ResponseToJSONTyped(value?: PrepareSubmission200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'files': value['files'] == null ? undefined : ((value['files'] as Array<any>).map(PrepareSubmission200ResponseFilesInnerToJSON)),
    };
}

