/* tslint:disable */
/* eslint-disable */
/**
 * EasyLog API Programmatic access to EasyLog REST endpoints
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
/**
 * @export
 * @interface PrepareSubmissionRequestFilesInner
 */
export interface PrepareSubmissionRequestFilesInner {
  /**
   * File name with extension
   *
   * @memberof PrepareSubmissionRequestFilesInner
   * @type {string}
   */
  name: string;
  /**
   * MIME type
   *
   * @memberof PrepareSubmissionRequestFilesInner
   * @type {string}
   */
  mime: string;
}

/**
 * Check if a given object implements the PrepareSubmissionRequestFilesInner
 * interface.
 */
export function instanceOfPrepareSubmissionRequestFilesInner(
  value: object
): value is PrepareSubmissionRequestFilesInner {
  if (!('name' in value) || value['name'] === undefined) return false;
  if (!('mime' in value) || value['mime'] === undefined) return false;
  return true;
}

export function PrepareSubmissionRequestFilesInnerFromJSON(
  json: any
): PrepareSubmissionRequestFilesInner {
  return PrepareSubmissionRequestFilesInnerFromJSONTyped(json, false);
}

export function PrepareSubmissionRequestFilesInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): PrepareSubmissionRequestFilesInner {
  if (json == null) {
    return json;
  }
  return {
    name: json['name'],
    mime: json['mime']
  };
}

export function PrepareSubmissionRequestFilesInnerToJSON(
  json: any
): PrepareSubmissionRequestFilesInner {
  return PrepareSubmissionRequestFilesInnerToJSONTyped(json, false);
}

export function PrepareSubmissionRequestFilesInnerToJSONTyped(
  value?: PrepareSubmissionRequestFilesInner | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    name: value['name'],
    mime: value['mime']
  };
}
