/* tslint:disable */
/* eslint-disable */
/**
 * EasyLog API Programmatic access to EasyLog REST endpoints
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
import type { PrepareSubmissionRequestFilesInner } from './PrepareSubmissionRequestFilesInner';
import {
  PrepareSubmissionRequestFilesInnerFromJSON,
  PrepareSubmissionRequestFilesInnerFromJSONTyped,
  PrepareSubmissionRequestFilesInnerToJSON,
  PrepareSubmissionRequestFilesInnerToJSONTyped
} from './PrepareSubmissionRequestFilesInner';

/**
 * @export
 * @interface PrepareSubmissionRequest
 */
export interface PrepareSubmissionRequest {
  /**
   * @memberof PrepareSubmissionRequest
   * @type {PrepareSubmissionRequestFilesInner[]}
   */
  files: Array<PrepareSubmissionRequestFilesInner>;
}

/** Check if a given object implements the PrepareSubmissionRequest interface. */
export function instanceOfPrepareSubmissionRequest(
  value: object
): value is PrepareSubmissionRequest {
  if (!('files' in value) || value['files'] === undefined) return false;
  return true;
}

export function PrepareSubmissionRequestFromJSON(
  json: any
): PrepareSubmissionRequest {
  return PrepareSubmissionRequestFromJSONTyped(json, false);
}

export function PrepareSubmissionRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): PrepareSubmissionRequest {
  if (json == null) {
    return json;
  }
  return {
    files: (json['files'] as Array<any>).map(
      PrepareSubmissionRequestFilesInnerFromJSON
    )
  };
}

export function PrepareSubmissionRequestToJSON(
  json: any
): PrepareSubmissionRequest {
  return PrepareSubmissionRequestToJSONTyped(json, false);
}

export function PrepareSubmissionRequestToJSONTyped(
  value?: PrepareSubmissionRequest | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    files: (value['files'] as Array<any>).map(
      PrepareSubmissionRequestFilesInnerToJSON
    )
  };
}
