/* tslint:disable */
/* eslint-disable */
/**
 * EasyLog API
 * Programmatic access to EasyLog REST endpoints
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProjectForm } from './ProjectForm';
import {
    ProjectFormFromJSON,
    ProjectFormFromJSONTyped,
    ProjectFormToJSON,
    ProjectFormToJSONTyped,
} from './ProjectForm';

/**
 * 
 * @export
 * @interface ProjectFormResource
 */
export interface ProjectFormResource {
    /**
     * 
     * @type {ProjectForm}
     * @memberof ProjectFormResource
     */
    data?: ProjectForm;
}

/**
 * Check if a given object implements the ProjectFormResource interface.
 */
export function instanceOfProjectFormResource(value: object): value is ProjectFormResource {
    return true;
}

export function ProjectFormResourceFromJSON(json: any): ProjectFormResource {
    return ProjectFormResourceFromJSONTyped(json, false);
}

export function ProjectFormResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectFormResource {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ProjectFormFromJSON(json['data']),
    };
}

export function ProjectFormResourceToJSON(json: any): ProjectFormResource {
    return ProjectFormResourceToJSONTyped(json, false);
}

export function ProjectFormResourceToJSONTyped(value?: ProjectFormResource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ProjectFormToJSON(value['data']),
    };
}

