/* tslint:disable */
/* eslint-disable */
/**
 * EasyLog API
 * Programmatic access to EasyLog REST endpoints
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginationLinks } from './PaginationLinks';
import {
    PaginationLinksFromJSON,
    PaginationLinksFromJSONTyped,
    PaginationLinksToJSON,
    PaginationLinksToJSONTyped,
} from './PaginationLinks';
import type { PaginationMeta } from './PaginationMeta';
import {
    PaginationMetaFromJSON,
    PaginationMetaFromJSONTyped,
    PaginationMetaToJSON,
    PaginationMetaToJSONTyped,
} from './PaginationMeta';
import type { Resource } from './Resource';
import {
    ResourceFromJSON,
    ResourceFromJSONTyped,
    ResourceToJSON,
    ResourceToJSONTyped,
} from './Resource';

/**
 * 
 * @export
 * @interface ResourceCollection
 */
export interface ResourceCollection {
    /**
     * 
     * @type {PaginationLinks}
     * @memberof ResourceCollection
     */
    links: PaginationLinks;
    /**
     * 
     * @type {PaginationMeta}
     * @memberof ResourceCollection
     */
    meta: PaginationMeta;
    /**
     * 
     * @type {Array<Resource>}
     * @memberof ResourceCollection
     */
    data: Array<Resource>;
}

/**
 * Check if a given object implements the ResourceCollection interface.
 */
export function instanceOfResourceCollection(value: object): value is ResourceCollection {
    if (!('links' in value) || value['links'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ResourceCollectionFromJSON(json: any): ResourceCollection {
    return ResourceCollectionFromJSONTyped(json, false);
}

export function ResourceCollectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourceCollection {
    if (json == null) {
        return json;
    }
    return {
        
        'links': PaginationLinksFromJSON(json['links']),
        'meta': PaginationMetaFromJSON(json['meta']),
        'data': ((json['data'] as Array<any>).map(ResourceFromJSON)),
    };
}

export function ResourceCollectionToJSON(json: any): ResourceCollection {
    return ResourceCollectionToJSONTyped(json, false);
}

export function ResourceCollectionToJSONTyped(value?: ResourceCollection | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'links': PaginationLinksToJSON(value['links']),
        'meta': PaginationMetaToJSON(value['meta']),
        'data': ((value['data'] as Array<any>).map(ResourceToJSON)),
    };
}

