/* tslint:disable */
/* eslint-disable */
/**
 * EasyLog API Programmatic access to EasyLog REST endpoints
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
import type { MediaDetailResource } from './MediaDetailResource';
import {
  MediaDetailResourceFromJSON,
  MediaDetailResourceFromJSONTyped,
  MediaDetailResourceToJSON,
  MediaDetailResourceToJSONTyped
} from './MediaDetailResource';

/**
 * @export
 * @interface ShowMedia200Response
 */
export interface ShowMedia200Response {
  /**
   * @memberof ShowMedia200Response
   * @type {MediaDetailResource}
   */
  data?: MediaDetailResource;
}

/** Check if a given object implements the ShowMedia200Response interface. */
export function instanceOfShowMedia200Response(
  value: object
): value is ShowMedia200Response {
  return true;
}

export function ShowMedia200ResponseFromJSON(json: any): ShowMedia200Response {
  return ShowMedia200ResponseFromJSONTyped(json, false);
}

export function ShowMedia200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ShowMedia200Response {
  if (json == null) {
    return json;
  }
  return {
    data:
      json['data'] == null
        ? undefined
        : MediaDetailResourceFromJSON(json['data'])
  };
}

export function ShowMedia200ResponseToJSON(json: any): ShowMedia200Response {
  return ShowMedia200ResponseToJSONTyped(json, false);
}

export function ShowMedia200ResponseToJSONTyped(
  value?: ShowMedia200Response | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    data: MediaDetailResourceToJSON(value['data'])
  };
}
