/* tslint:disable */
/* eslint-disable */
/**
 * EasyLog API Programmatic access to EasyLog REST endpoints
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
import type { Submission } from './Submission';
import {
  SubmissionFromJSON,
  SubmissionFromJSONTyped,
  SubmissionToJSON,
  SubmissionToJSONTyped
} from './Submission';

/**
 * @export
 * @interface ShowSubmission200Response
 */
export interface ShowSubmission200Response {
  /**
   * @memberof ShowSubmission200Response
   * @type {Submission}
   */
  data?: Submission;
}

/** Check if a given object implements the ShowSubmission200Response interface. */
export function instanceOfShowSubmission200Response(
  value: object
): value is ShowSubmission200Response {
  return true;
}

export function ShowSubmission200ResponseFromJSON(
  json: any
): ShowSubmission200Response {
  return ShowSubmission200ResponseFromJSONTyped(json, false);
}

export function ShowSubmission200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ShowSubmission200Response {
  if (json == null) {
    return json;
  }
  return {
    data: json['data'] == null ? undefined : SubmissionFromJSON(json['data'])
  };
}

export function ShowSubmission200ResponseToJSON(
  json: any
): ShowSubmission200Response {
  return ShowSubmission200ResponseToJSONTyped(json, false);
}

export function ShowSubmission200ResponseToJSONTyped(
  value?: ShowSubmission200Response | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    data: SubmissionToJSON(value['data'])
  };
}
