/* tslint:disable */
/* eslint-disable */
/**
 * EasyLog API Programmatic access to EasyLog REST endpoints
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
/**
 * @export
 * @interface ShowDatasourceEntry200Response
 */
export interface ShowDatasourceEntry200Response {
  /**
   * Entity datum data
   *
   * @memberof ShowDatasourceEntry200Response
   * @type {{ [key: string]: any }}
   */
  data?: { [key: string]: any };
}

/**
 * Check if a given object implements the ShowDatasourceEntry200Response
 * interface.
 */
export function instanceOfShowDatasourceEntry200Response(
  value: object
): value is ShowDatasourceEntry200Response {
  return true;
}

export function ShowDatasourceEntry200ResponseFromJSON(
  json: any
): ShowDatasourceEntry200Response {
  return ShowDatasourceEntry200ResponseFromJSONTyped(json, false);
}

export function ShowDatasourceEntry200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ShowDatasourceEntry200Response {
  if (json == null) {
    return json;
  }
  return {
    data: json['data'] == null ? undefined : json['data']
  };
}

export function ShowDatasourceEntry200ResponseToJSON(
  json: any
): ShowDatasourceEntry200Response {
  return ShowDatasourceEntry200ResponseToJSONTyped(json, false);
}

export function ShowDatasourceEntry200ResponseToJSONTyped(
  value?: ShowDatasourceEntry200Response | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    data: value['data']
  };
}
