/* tslint:disable */
/* eslint-disable */
/**
 * EasyLog API Programmatic access to EasyLog REST endpoints
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
import type { Resource } from './Resource';
import {
  ResourceFromJSON,
  ResourceFromJSONTyped,
  ResourceToJSON,
  ResourceToJSONTyped
} from './Resource';

/**
 * @export
 * @interface ShowResourceByGroup200Response
 */
export interface ShowResourceByGroup200Response {
  /**
   * @memberof ShowResourceByGroup200Response
   * @type {Resource}
   */
  data: Resource;
}

/**
 * Check if a given object implements the ShowResourceByGroup200Response
 * interface.
 */
export function instanceOfShowResourceByGroup200Response(
  value: object
): value is ShowResourceByGroup200Response {
  if (!('data' in value) || value['data'] === undefined) return false;
  return true;
}

export function ShowResourceByGroup200ResponseFromJSON(
  json: any
): ShowResourceByGroup200Response {
  return ShowResourceByGroup200ResponseFromJSONTyped(json, false);
}

export function ShowResourceByGroup200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ShowResourceByGroup200Response {
  if (json == null) {
    return json;
  }
  return {
    data: ResourceFromJSON(json['data'])
  };
}

export function ShowResourceByGroup200ResponseToJSON(
  json: any
): ShowResourceByGroup200Response {
  return ShowResourceByGroup200ResponseToJSONTyped(json, false);
}

export function ShowResourceByGroup200ResponseToJSONTyped(
  value?: ShowResourceByGroup200Response | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    data: ResourceToJSON(value['data'])
  };
}
