/* tslint:disable */
/* eslint-disable */
/**
 * EasyLog API
 * Programmatic access to EasyLog REST endpoints
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Entity } from './Entity';
import {
    EntityFromJSON,
    EntityFromJSONTyped,
    EntityToJSON,
    EntityToJSONTyped,
} from './Entity';

/**
 * 
 * @export
 * @interface ShowDatasource200Response
 */
export interface ShowDatasource200Response {
    /**
     * 
     * @type {Entity}
     * @memberof ShowDatasource200Response
     */
    data: Entity;
}

/**
 * Check if a given object implements the ShowDatasource200Response interface.
 */
export function instanceOfShowDatasource200Response(value: object): value is ShowDatasource200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ShowDatasource200ResponseFromJSON(json: any): ShowDatasource200Response {
    return ShowDatasource200ResponseFromJSONTyped(json, false);
}

export function ShowDatasource200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShowDatasource200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': EntityFromJSON(json['data']),
    };
}

export function ShowDatasource200ResponseToJSON(json: any): ShowDatasource200Response {
    return ShowDatasource200ResponseToJSONTyped(json, false);
}

export function ShowDatasource200ResponseToJSONTyped(value?: ShowDatasource200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': EntityToJSON(value['data']),
    };
}

