/* tslint:disable */
/* eslint-disable */
/**
 * EasyLog API
 * Programmatic access to EasyLog REST endpoints
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StoreFollowUpInput
 */
export interface StoreFollowUpInput {
    /**
     * 
     * @type {string}
     * @memberof StoreFollowUpInput
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof StoreFollowUpInput
     */
    slug: string;
    /**
     * 
     * @type {string}
     * @memberof StoreFollowUpInput
     */
    description?: string | null;
    /**
     * 
     * @type {number}
     * @memberof StoreFollowUpInput
     */
    followUpCategoryId?: number | null;
    /**
     * 
     * @type {string}
     * @memberof StoreFollowUpInput
     */
    icon?: string | null;
    /**
     * 
     * @type {object}
     * @memberof StoreFollowUpInput
     */
    scheme: object;
    /**
     * 
     * @type {boolean}
     * @memberof StoreFollowUpInput
     */
    canUseJsonTable?: boolean | null;
}

/**
 * Check if a given object implements the StoreFollowUpInput interface.
 */
export function instanceOfStoreFollowUpInput(value: object): value is StoreFollowUpInput {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('scheme' in value) || value['scheme'] === undefined) return false;
    return true;
}

export function StoreFollowUpInputFromJSON(json: any): StoreFollowUpInput {
    return StoreFollowUpInputFromJSONTyped(json, false);
}

export function StoreFollowUpInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoreFollowUpInput {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'slug': json['slug'],
        'description': json['description'] == null ? undefined : json['description'],
        'followUpCategoryId': json['follow_up_category_id'] == null ? undefined : json['follow_up_category_id'],
        'icon': json['icon'] == null ? undefined : json['icon'],
        'scheme': json['scheme'],
        'canUseJsonTable': json['can_use_json_table'] == null ? undefined : json['can_use_json_table'],
    };
}

export function StoreFollowUpInputToJSON(json: any): StoreFollowUpInput {
    return StoreFollowUpInputToJSONTyped(json, false);
}

export function StoreFollowUpInputToJSONTyped(value?: StoreFollowUpInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'slug': value['slug'],
        'description': value['description'],
        'follow_up_category_id': value['followUpCategoryId'],
        'icon': value['icon'],
        'scheme': value['scheme'],
        'can_use_json_table': value['canUseJsonTable'],
    };
}

