/* tslint:disable */
/* eslint-disable */
/**
 * EasyLog API Programmatic access to EasyLog REST endpoints
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
import type { Submission } from './Submission';
import {
  SubmissionFromJSON,
  SubmissionFromJSONTyped,
  SubmissionToJSON,
  SubmissionToJSONTyped
} from './Submission';

/**
 * @export
 * @interface SubmissionCollection
 */
export interface SubmissionCollection {
  /**
   * @memberof SubmissionCollection
   * @type {Submission[]}
   */
  data?: Array<Submission>;
}

/** Check if a given object implements the SubmissionCollection interface. */
export function instanceOfSubmissionCollection(
  value: object
): value is SubmissionCollection {
  return true;
}

export function SubmissionCollectionFromJSON(json: any): SubmissionCollection {
  return SubmissionCollectionFromJSONTyped(json, false);
}

export function SubmissionCollectionFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): SubmissionCollection {
  if (json == null) {
    return json;
  }
  return {
    data:
      json['data'] == null
        ? undefined
        : (json['data'] as Array<any>).map(SubmissionFromJSON)
  };
}

export function SubmissionCollectionToJSON(json: any): SubmissionCollection {
  return SubmissionCollectionToJSONTyped(json, false);
}

export function SubmissionCollectionToJSONTyped(
  value?: SubmissionCollection | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    data:
      value['data'] == null
        ? undefined
        : (value['data'] as Array<any>).map(SubmissionToJSON)
  };
}
