/* tslint:disable */
/* eslint-disable */
/**
 * EasyLog API Programmatic access to EasyLog REST endpoints
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
/**
 * @export
 * @interface Submission
 */
export interface Submission {
  /**
   * @memberof Submission
   * @type {number}
   */
  id?: number;
  /**
   * @memberof Submission
   * @type {number}
   */
  issuerId?: number;
  /**
   * @memberof Submission
   * @type {number}
   */
  clientId?: number;
  /**
   * @memberof Submission
   * @type {number}
   */
  projectFormId?: number;
  /**
   * @memberof Submission
   * @type {number}
   */
  versionId?: number | null;
  /**
   * @memberof Submission
   * @type {object}
   */
  data?: object | null;
  /**
   * @memberof Submission
   * @type {string}
   */
  checksum?: string;
  /**
   * @memberof Submission
   * @type {Date}
   */
  createdAt?: Date | null;
  /**
   * @memberof Submission
   * @type {Date}
   */
  updatedAt?: Date | null;
}

/** Check if a given object implements the Submission interface. */
export function instanceOfSubmission(value: object): value is Submission {
  return true;
}

export function SubmissionFromJSON(json: any): Submission {
  return SubmissionFromJSONTyped(json, false);
}

export function SubmissionFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): Submission {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'] == null ? undefined : json['id'],
    issuerId: json['issuer_id'] == null ? undefined : json['issuer_id'],
    clientId: json['client_id'] == null ? undefined : json['client_id'],
    projectFormId:
      json['project_form_id'] == null ? undefined : json['project_form_id'],
    versionId: json['version_id'] == null ? undefined : json['version_id'],
    data: json['data'] == null ? undefined : json['data'],
    checksum: json['checksum'] == null ? undefined : json['checksum'],
    createdAt:
      json['created_at'] == null ? undefined : new Date(json['created_at']),
    updatedAt:
      json['updated_at'] == null ? undefined : new Date(json['updated_at'])
  };
}

export function SubmissionToJSON(json: any): Submission {
  return SubmissionToJSONTyped(json, false);
}

export function SubmissionToJSONTyped(
  value?: Submission | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    issuer_id: value['issuerId'],
    client_id: value['clientId'],
    project_form_id: value['projectFormId'],
    version_id: value['versionId'],
    data: value['data'],
    checksum: value['checksum'],
    created_at:
      value['createdAt'] == null
        ? undefined
        : (value['createdAt'] as any).toISOString(),
    updated_at:
      value['updatedAt'] == null
        ? undefined
        : (value['updatedAt'] as any).toISOString()
  };
}
