/* tslint:disable */
/* eslint-disable */
/**
 * EasyLog API
 * Programmatic access to EasyLog REST endpoints
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Submission } from './Submission';
import {
    SubmissionFromJSON,
    SubmissionFromJSONTyped,
    SubmissionToJSON,
    SubmissionToJSONTyped,
} from './Submission';

/**
 * 
 * @export
 * @interface SubmissionResource
 */
export interface SubmissionResource {
    /**
     * 
     * @type {Submission}
     * @memberof SubmissionResource
     */
    data?: Submission;
}

/**
 * Check if a given object implements the SubmissionResource interface.
 */
export function instanceOfSubmissionResource(value: object): value is SubmissionResource {
    return true;
}

export function SubmissionResourceFromJSON(json: any): SubmissionResource {
    return SubmissionResourceFromJSONTyped(json, false);
}

export function SubmissionResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubmissionResource {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : SubmissionFromJSON(json['data']),
    };
}

export function SubmissionResourceToJSON(json: any): SubmissionResource {
    return SubmissionResourceToJSONTyped(json, false);
}

export function SubmissionResourceToJSONTyped(value?: SubmissionResource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': SubmissionToJSON(value['data']),
    };
}

