/* tslint:disable */
/* eslint-disable */
/**
 * EasyLog API Programmatic access to EasyLog REST endpoints
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
/**
 * @export
 * @interface UpdateSubmissionInput
 */
export interface UpdateSubmissionInput {
  /**
   * Submission data (JSON object)
   *
   * @memberof UpdateSubmissionInput
   * @type {object}
   */
  data?: object;
}

/** Check if a given object implements the UpdateSubmissionInput interface. */
export function instanceOfUpdateSubmissionInput(
  value: object
): value is UpdateSubmissionInput {
  return true;
}

export function UpdateSubmissionInputFromJSON(
  json: any
): UpdateSubmissionInput {
  return UpdateSubmissionInputFromJSONTyped(json, false);
}

export function UpdateSubmissionInputFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): UpdateSubmissionInput {
  if (json == null) {
    return json;
  }
  return {
    data: json['data'] == null ? undefined : json['data']
  };
}

export function UpdateSubmissionInputToJSON(json: any): UpdateSubmissionInput {
  return UpdateSubmissionInputToJSONTyped(json, false);
}

export function UpdateSubmissionInputToJSONTyped(
  value?: UpdateSubmissionInput | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    data: value['data']
  };
}
