/* tslint:disable */
/* eslint-disable */
/**
 * EasyLog API
 * Programmatic access to EasyLog REST endpoints
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateFormInput
 */
export interface UpdateFormInput {
    /**
     * 
     * @type {string}
     * @memberof UpdateFormInput
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateFormInput
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateFormInput
     */
    avatar?: string | null;
    /**
     * JSON string containing form schema
     * @type {string}
     * @memberof UpdateFormInput
     */
    content?: string;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateFormInput
     */
    forceSchemaValidity?: boolean | null;
}

/**
 * Check if a given object implements the UpdateFormInput interface.
 */
export function instanceOfUpdateFormInput(value: object): value is UpdateFormInput {
    return true;
}

export function UpdateFormInputFromJSON(json: any): UpdateFormInput {
    return UpdateFormInputFromJSONTyped(json, false);
}

export function UpdateFormInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateFormInput {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'avatar': json['avatar'] == null ? undefined : json['avatar'],
        'content': json['content'] == null ? undefined : json['content'],
        'forceSchemaValidity': json['force_schema_validity'] == null ? undefined : json['force_schema_validity'],
    };
}

export function UpdateFormInputToJSON(json: any): UpdateFormInput {
    return UpdateFormInputToJSONTyped(json, false);
}

export function UpdateFormInputToJSONTyped(value?: UpdateFormInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'avatar': value['avatar'],
        'content': value['content'],
        'force_schema_validity': value['forceSchemaValidity'],
    };
}

