/* tslint:disable */
/* eslint-disable */
/**
 * EasyLog API
 * Programmatic access to EasyLog REST endpoints
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MediaResource } from './MediaResource';
import {
    MediaResourceFromJSON,
    MediaResourceFromJSONTyped,
    MediaResourceToJSON,
    MediaResourceToJSONTyped,
} from './MediaResource';

/**
 * 
 * @export
 * @interface UploadSubmissionMedia201Response
 */
export interface UploadSubmissionMedia201Response {
    /**
     * 
     * @type {MediaResource}
     * @memberof UploadSubmissionMedia201Response
     */
    data?: MediaResource;
}

/**
 * Check if a given object implements the UploadSubmissionMedia201Response interface.
 */
export function instanceOfUploadSubmissionMedia201Response(value: object): value is UploadSubmissionMedia201Response {
    return true;
}

export function UploadSubmissionMedia201ResponseFromJSON(json: any): UploadSubmissionMedia201Response {
    return UploadSubmissionMedia201ResponseFromJSONTyped(json, false);
}

export function UploadSubmissionMedia201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadSubmissionMedia201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : MediaResourceFromJSON(json['data']),
    };
}

export function UploadSubmissionMedia201ResponseToJSON(json: any): UploadSubmissionMedia201Response {
    return UploadSubmissionMedia201ResponseToJSONTyped(json, false);
}

export function UploadSubmissionMedia201ResponseToJSONTyped(value?: UploadSubmissionMedia201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': MediaResourceToJSON(value['data']),
    };
}

