/* tslint:disable */
/* eslint-disable */
/**
 * EasyLog API Programmatic access to EasyLog REST endpoints
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { mapValues } from '../runtime';
import type { MediaResource } from './MediaResource';
import {
  MediaResourceFromJSON,
  MediaResourceFromJSONTyped,
  MediaResourceToJSON,
  MediaResourceToJSONTyped
} from './MediaResource';

/**
 * @export
 * @interface UploadFollowUpEntryMedia201Response
 */
export interface UploadFollowUpEntryMedia201Response {
  /**
   * @memberof UploadFollowUpEntryMedia201Response
   * @type {MediaResource}
   */
  data?: MediaResource;
  /**
   * Path in PATH format
   * ({clientId}/notices/{timestamp}-{sanitized}.{ext}--ORIG--{base64}). Use
   * this to update the appropriate data field.
   *
   * @memberof UploadFollowUpEntryMedia201Response
   * @type {string}
   */
  path?: string;
}

/**
 * Check if a given object implements the UploadFollowUpEntryMedia201Response
 * interface.
 */
export function instanceOfUploadFollowUpEntryMedia201Response(
  value: object
): value is UploadFollowUpEntryMedia201Response {
  return true;
}

export function UploadFollowUpEntryMedia201ResponseFromJSON(
  json: any
): UploadFollowUpEntryMedia201Response {
  return UploadFollowUpEntryMedia201ResponseFromJSONTyped(json, false);
}

export function UploadFollowUpEntryMedia201ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): UploadFollowUpEntryMedia201Response {
  if (json == null) {
    return json;
  }
  return {
    data:
      json['data'] == null ? undefined : MediaResourceFromJSON(json['data']),
    path: json['path'] == null ? undefined : json['path']
  };
}

export function UploadFollowUpEntryMedia201ResponseToJSON(
  json: any
): UploadFollowUpEntryMedia201Response {
  return UploadFollowUpEntryMedia201ResponseToJSONTyped(json, false);
}

export function UploadFollowUpEntryMedia201ResponseToJSONTyped(
  value?: UploadFollowUpEntryMedia201Response | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    data: MediaResourceToJSON(value['data']),
    path: value['path']
  };
}
