/* tslint:disable */
/* eslint-disable */
/**
 * EasyLog API Programmatic access to EasyLog REST endpoints
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import * as runtime from '../runtime';
import type { BulletinChapterCollection } from '../models/index';
import {
  BulletinChapterCollectionFromJSON,
  BulletinChapterCollectionToJSON
} from '../models/index';

export class BulletinApi extends runtime.BaseAPI {
  /**
   * Get all bulletin chapters with their items, organized hierarchically.
   * Includes items not assigned to any chapter as a synthetic first chapter
   * with id=0. Only returns chapters and items accessible to the user's groups.
   * List bulletin chapters and items
   */
  async listBulletinItemsRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<BulletinChapterCollection>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters['Authorization'] = await this.configuration.accessToken(
        'passport',
        []
      );
    }

    let urlPath = `/v2/bulletin-items`;

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      BulletinChapterCollectionFromJSON(jsonValue)
    );
  }

  /**
   * Get all bulletin chapters with their items, organized hierarchically.
   * Includes items not assigned to any chapter as a synthetic first chapter
   * with id=0. Only returns chapters and items accessible to the user's groups.
   * List bulletin chapters and items
   */
  async listBulletinItems(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<BulletinChapterCollection> {
    const response = await this.listBulletinItemsRaw(initOverrides);
    return await response.value();
  }
}
