/* tslint:disable */
/* eslint-disable */
/**
 * EasyLog API Programmatic access to EasyLog REST endpoints
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import * as runtime from '../runtime';

export interface ExportCalendarICSRequest {
  token: string;
}

export class CalendarApi extends runtime.BaseAPI {
  /**
   * Export allocations for a resource as an iCalendar (.ics) file using a
   * secure token. Returns text/calendar format. Export resource calendar as
   * ICS
   */
  async exportCalendarICSRaw(
    requestParameters: ExportCalendarICSRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Blob>> {
    if (requestParameters['token'] == null) {
      throw new runtime.RequiredError(
        'token',
        'Required parameter "token" was null or undefined when calling exportCalendarICS().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/v2/calendar/{token}/ics`;
    urlPath = urlPath.replace(
      `{${'token'}}`,
      encodeURIComponent(String(requestParameters['token']))
    );

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters
      },
      initOverrides
    );

    return new runtime.BlobApiResponse(response);
  }

  /**
   * Export allocations for a resource as an iCalendar (.ics) file using a
   * secure token. Returns text/calendar format. Export resource calendar as
   * ICS
   */
  async exportCalendarICS(
    requestParameters: ExportCalendarICSRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Blob> {
    const response = await this.exportCalendarICSRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }
}
