/* tslint:disable */
/* eslint-disable */
/**
 * EasyLog API Programmatic access to EasyLog REST endpoints
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import * as runtime from '../runtime';
import type { ClientConfigurationResource } from '../models/index';
import {
  ClientConfigurationResourceFromJSON,
  ClientConfigurationResourceToJSON
} from '../models/index';

export class ConfigurationApi extends runtime.BaseAPI {
  /**
   * Retrieve the authenticated user's client configuration including default
   * time periods, planning filters, and permissions. Get client configuration
   */
  async getClientConfigurationRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<ClientConfigurationResource>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters['Authorization'] = await this.configuration.accessToken(
        'passport',
        []
      );
    }

    let urlPath = `/v2/configuration`;

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ClientConfigurationResourceFromJSON(jsonValue)
    );
  }

  /**
   * Retrieve the authenticated user's client configuration including default
   * time periods, planning filters, and permissions. Get client configuration
   */
  async getClientConfiguration(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<ClientConfigurationResource> {
    const response = await this.getClientConfigurationRaw(initOverrides);
    return await response.value();
  }
}
