/* tslint:disable */
/* eslint-disable */
/**
 * EasyLog API Programmatic access to EasyLog REST endpoints
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import * as runtime from '../runtime';
import type { MediaDetailResource } from '../models/index';
import {
  MediaDetailResourceFromJSON,
  MediaDetailResourceToJSON
} from '../models/index';

export interface ShowMediaRequest {
  media: string;
  conversion?: string;
}

export class MediaApi extends runtime.BaseAPI {
  /**
   * Get media file details including presigned download URL (valid for 1 hour)
   * and available image conversions. Supports both numeric ID and UUID. Show
   * media file
   */
  async showMediaRaw(
    requestParameters: ShowMediaRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<MediaDetailResource>> {
    if (requestParameters['media'] == null) {
      throw new runtime.RequiredError(
        'media',
        'Required parameter "media" was null or undefined when calling showMedia().'
      );
    }

    const queryParameters: any = {};

    if (requestParameters['conversion'] != null) {
      queryParameters['conversion'] = requestParameters['conversion'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters['Authorization'] = await this.configuration.accessToken(
        'passport',
        []
      );
    }

    const response = await this.request(
      {
        path: `/v2/media/{media}`.replace(
          `{${'media'}}`,
          encodeURIComponent(String(requestParameters['media']))
        ),
        method: 'GET',
        headers: headerParameters,
        query: queryParameters
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      MediaDetailResourceFromJSON(jsonValue)
    );
  }

  /**
   * Get media file details including presigned download URL (valid for 1 hour)
   * and available image conversions. Supports both numeric ID and UUID. Show
   * media file
   */
  async showMedia(
    requestParameters: ShowMediaRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<MediaDetailResource> {
    const response = await this.showMediaRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
