/* tslint:disable */
/* eslint-disable */
/**
 * EasyLog API
 * Programmatic access to EasyLog REST endpoints
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Phase,
  PhaseCreatePayload,
  PhaseUpdatePayload,
} from '../models/index';
import {
    PhaseFromJSON,
    PhaseToJSON,
    PhaseCreatePayloadFromJSON,
    PhaseCreatePayloadToJSON,
    PhaseUpdatePayloadFromJSON,
    PhaseUpdatePayloadToJSON,
} from '../models/index';

export interface 0311da1cea655bc2d1604d7d41b7bfd9Request {
    phase: number;
}

export interface 0d3e5e87594938822a3f4342dad62f36Request {
    phase: number;
}

export interface 83ce4b16b2af73d27a64fb48ae1fc62fRequest {
    project: number;
}

export interface Ad1d21e7985e497ed7c5ff220ac5ead2Request {
    phase: number;
    phaseUpdatePayload: PhaseUpdatePayload;
}

export interface D675b0fdc020c9506b62049495c84c4dRequest {
    project: number;
    phaseCreatePayload: PhaseCreatePayload;
}

/**
 * 
 */
export class PlanningPhasesApi extends runtime.BaseAPI {

    /**
     * Delete phase
     */
    async _0311da1cea655bc2d1604d7d41b7bfd9Raw(requestParameters: 0311da1cea655bc2d1604d7d41b7bfd9Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['phase'] == null) {
            throw new runtime.RequiredError(
                'phase',
                'Required parameter "phase" was null or undefined when calling _0311da1cea655bc2d1604d7d41b7bfd9().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v2/datasources/phases/{phase}`;
        urlPath = urlPath.replace(`{${"phase"}}`, encodeURIComponent(String(requestParameters['phase'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete phase
     */
    async _0311da1cea655bc2d1604d7d41b7bfd9(requestParameters: 0311da1cea655bc2d1604d7d41b7bfd9Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this._0311da1cea655bc2d1604d7d41b7bfd9Raw(requestParameters, initOverrides);
    }

    /**
     * Show phase
     */
    async _0d3e5e87594938822a3f4342dad62f36Raw(requestParameters: 0d3e5e87594938822a3f4342dad62f36Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Phase>> {
        if (requestParameters['phase'] == null) {
            throw new runtime.RequiredError(
                'phase',
                'Required parameter "phase" was null or undefined when calling _0d3e5e87594938822a3f4342dad62f36().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v2/datasources/phases/{phase}`;
        urlPath = urlPath.replace(`{${"phase"}}`, encodeURIComponent(String(requestParameters['phase'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PhaseFromJSON(jsonValue));
    }

    /**
     * Show phase
     */
    async _0d3e5e87594938822a3f4342dad62f36(requestParameters: 0d3e5e87594938822a3f4342dad62f36Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Phase> {
        const response = await this._0d3e5e87594938822a3f4342dad62f36Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List project phases
     */
    async _83ce4b16b2af73d27a64fb48ae1fc62fRaw(requestParameters: 83ce4b16b2af73d27a64fb48ae1fc62fRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Phase>>> {
        if (requestParameters['project'] == null) {
            throw new runtime.RequiredError(
                'project',
                'Required parameter "project" was null or undefined when calling _83ce4b16b2af73d27a64fb48ae1fc62f().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v2/datasources/project/{project}/phases`;
        urlPath = urlPath.replace(`{${"project"}}`, encodeURIComponent(String(requestParameters['project'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PhaseFromJSON));
    }

    /**
     * List project phases
     */
    async _83ce4b16b2af73d27a64fb48ae1fc62f(requestParameters: 83ce4b16b2af73d27a64fb48ae1fc62fRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Phase>> {
        const response = await this._83ce4b16b2af73d27a64fb48ae1fc62fRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update phase
     */
    async ad1d21e7985e497ed7c5ff220ac5ead2Raw(requestParameters: Ad1d21e7985e497ed7c5ff220ac5ead2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Phase>> {
        if (requestParameters['phase'] == null) {
            throw new runtime.RequiredError(
                'phase',
                'Required parameter "phase" was null or undefined when calling ad1d21e7985e497ed7c5ff220ac5ead2().'
            );
        }

        if (requestParameters['phaseUpdatePayload'] == null) {
            throw new runtime.RequiredError(
                'phaseUpdatePayload',
                'Required parameter "phaseUpdatePayload" was null or undefined when calling ad1d21e7985e497ed7c5ff220ac5ead2().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v2/datasources/phases/{phase}`;
        urlPath = urlPath.replace(`{${"phase"}}`, encodeURIComponent(String(requestParameters['phase'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PhaseUpdatePayloadToJSON(requestParameters['phaseUpdatePayload']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PhaseFromJSON(jsonValue));
    }

    /**
     * Update phase
     */
    async ad1d21e7985e497ed7c5ff220ac5ead2(requestParameters: Ad1d21e7985e497ed7c5ff220ac5ead2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Phase> {
        const response = await this.ad1d21e7985e497ed7c5ff220ac5ead2Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create project phase
     */
    async d675b0fdc020c9506b62049495c84c4dRaw(requestParameters: D675b0fdc020c9506b62049495c84c4dRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Phase>> {
        if (requestParameters['project'] == null) {
            throw new runtime.RequiredError(
                'project',
                'Required parameter "project" was null or undefined when calling d675b0fdc020c9506b62049495c84c4d().'
            );
        }

        if (requestParameters['phaseCreatePayload'] == null) {
            throw new runtime.RequiredError(
                'phaseCreatePayload',
                'Required parameter "phaseCreatePayload" was null or undefined when calling d675b0fdc020c9506b62049495c84c4d().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v2/datasources/project/{project}/phases`;
        urlPath = urlPath.replace(`{${"project"}}`, encodeURIComponent(String(requestParameters['project'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PhaseCreatePayloadToJSON(requestParameters['phaseCreatePayload']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PhaseFromJSON(jsonValue));
    }

    /**
     * Create project phase
     */
    async d675b0fdc020c9506b62049495c84c4d(requestParameters: D675b0fdc020c9506b62049495c84c4dRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Phase> {
        const response = await this.d675b0fdc020c9506b62049495c84c4dRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
