// Generated by ts-to-zod
import { z } from 'zod';

export const heroContactSchema = z.object({
  email: z.string(),
  name: z.string()
});

const uIMessageAiSchema = z.any();

export const uIMessageSchema = uIMessageAiSchema;
